### ISSUE TITLE
Suggestion re: new Timblock display on Proposals Page

### ISSUE THREAD

**Issue by PhilipKelley** [neinteractiveliterature/intercode#1187]
On some forms I'm seeing a blank space for some timblocks, where the proposer selected "Don't Care". This is a bit confusing, as there are also blank spots for invalid blocks (Thursday AM, Sunday PM). I think it would be less confusing to have something displayed there, such as "Ok", to differentiate it from the empty non-blocks.

Very minor idea, perhaps instead of long words (Not Available, 1st Choice, etc.), use short (1st, 2nd, Ok, N/A)? It *might* be easier to take in what's what in a glance this way. Opinions will vary on this. And, actually, leaving "Not Available" might help the available blocks stand out better. Wading through a 60 - 80 of these at scheduling time, anything to make it easier is good. Again, just a suggestion.

**Comment by nbudin** [comment]
Yeah, I think putting "Don't Care" would be a good idea.  Part of the point of this visual refresh was to get the proposal committee's view to show exactly what the user thought they were selecting, as close as possible to how they saw it.  So if they pick "Don't Care", you should see "Don't Care".

For that reason, I'd rather not abbreviate.  But I do think it would be a good idea to somehow make the table easier to scan visually.  I'm thinking of maybe coloring the table cells to indicate the preference; not sure exactly how to do it yet but I'll play around with it.

@dkapell, if you have any thoughts here, please add them as well.

**Comment by dkapell** [comment]
I'd make two changes:
1. Use `.table-sm` to compress the table a bit
2. Color code as follows:
Invalid block (before or after con) `.table-secondary`
1st-3rd choice `. table-success`
Don't Care `.table-warning`
Not Available `.table-danger`

**Comment by nbudin** [comment]
OK, pushing an improved version shortly.  Here's a picture of what that'll do:

![screenshot 2018-08-23 08 35 54](https://user-images.githubusercontent.com/7477/44536519-ac5a3e00-a6ca-11e8-88d2-6d9b223a1add.png)
