### ISSUE TITLE
Bug, but only in IE

### ISSUE THREAD

**Issue by PhilipKelley** [neinteractiveliterature/intercode#1371]
Found a bug that only crops up in IE (11 -- current work default, because of Legacy). It works in Chrome and Firefox, so not a serious problem, but it or something related might be an issue for some users?

Logged on to site at work, using Internet Explorer (11)

Went to Event Proposals page
Items were listed by, uh, it loos random. Maybe by an internal (not displayed) proposal Id?
Clicked on “Submitted” column header, to order by that. Got Error screen, with pink bar containing text “Invalid attempt to spread non-iterable instance”
Backspace takes me to home page.
Return to Events proposal, use Status dropdown, click on “Reviewing”. Am immediately take to same error page with same message.

Then flipped over to Chrome, had no problems.
I use Firefox at home, no problems there either.

(If I had to guess, I'd say it has to do with the recent "open in new tab" fix applied to this page.)

**Comment by nbudin** [comment]
This is almost certainly these two Rollbars:

* https://rollbar.com/neinteractiveliterature/intercode/items/149/
* https://rollbar.com/neinteractiveliterature/intercode/items/148/

**Comment by nbudin** [comment]
"Fixed" this one by dropping support for IE11.  (I realize that is possibly the worst way to fix a bug, but it pretty much had to be done for other reasons anyway.)
