### ISSUE TITLE
UI improvements, and enforcing required fields, in event editing (and possibly profile editing?)

### ISSUE THREAD

**Issue by PhilipKelley** [neinteractiveliterature/intercode#1372]
Had a question from a GM whose game was just accepted. Did some poking around, and found inconsistancies. Note that this may apply to more than just the "Author" field.
 - Proposal form has "Author(s)" and "Organization" fields. GM enters these or not, both are optional.
 - Fields may be modified at any time, both before and after game is accepted
 - Once game is accepted... how does it work? Is an "Event" created, that is different from a Proposal? Ah hah--Proposal can no longer be modified! (Might be good to now display "Frozen", or some such.)
 - Event is now public and available and *can* be modified. Here, "Author(s)" and "Organization" can be set or reset.
 - For Events, "Author(s)" is displayed; if blank, "Organization" will be displayed; if both are blank, neither is displayed.

So confusion comes in because:
 - GM submitted proposal, with no Organization and possibly no no Author
 - GM later modified Author--either added it, or modified it (I don't know which, but there definitely was a change)
 - Game was accepted. Lo and behold, in the Event Author (and Organization) are blank--revised Author text did not carry through.

So, something odd going on here.

Additional thoughts re: "Edit Event" screen, since I haven't seen it yet, and nether has most anyone else.
- Have "Save" button at top as well as bottom of screen?
- Have "Cancel" button as well. Yes, backspace works, but even so.
- Huh. I see a red star next to Author(s), where this field is blank. Ditto other fields, though they are not blank. Can save if changed from text to blank? What if was blank, and is being left blank? (Not my game, I'm not testing anything.)
- Presuming text describing fields is same as from Proposals page. This is cool.
- I can see and appear to have access to the "Override event-provided badge quotas" fields. Should I, as PropCom Chair? (Totally NOT messing around with these to see how the work, or if they are disabled.)

**Comment by nbudin** [comment]
The missing fields are likely the result of a bug I'd noticed as well: #1363 

There are some definite UI weirdnesses about that page; it's somewhat a victim of the switch to adminable event forms that we did a few months ago (basically, I never reconsidered the design of this page after making that change).  It's certainly worth another once-over.

As far as the overriding badge quotas, that's on purpose - the proposal chair is supposed to be able to do that (so that, if a convention wants, they can make that part of the proposal acceptance process).

**Comment by nbudin** [comment]
Changing the title of this to more accurately reflect the work that's left to be done after fixing the author bug.
