### ISSUE TITLE
No space, you can hear someone scream

### ISSUE THREAD

**Issue by diewald** [neinteractiveliterature/intercode#1373]
I'm adding Julie to the GM list for Adrift on the Starry Sky. Julie does not have a badge yet. So, the text says "Julie Diewald has nobadge forIntercon S. Without..." There are two obviously missing spaces in the sentence. "...no badge for Intercon..."

**Comment by nbudin** [comment]
Lol, A+ issue title 😂 

Thanks for this, a fix should be pushing to production shortly.
