### ISSUE TITLE
URLs to outside domains should be parsed and have a scheme added if needed

### ISSUE THREAD

**Issue by chadberg** [neinteractiveliterature/intercode#1457]
In looking at the description for Brian's game at https://s.interconlarp.org/events/28 I clicked on the link to the game website.....

which was not prepended with the URL scheme http:// or https://.....

so I was brought to a relative page of https://s.interconlarp.org/events/www.nnbtv.org.uk/Games/Games.html....

which doesn't exist.

Either we should force game submitters to submit a proper URL (parse and error if no scheme) or we should prepend one for them. Which can be awkward and carries its own risks, so I advocate for approach 1.

**Comment by dkapell** [comment]
I have edited the game to add 'http://' to the url for now.  I agree that that field should validate as URL, if we already have a URL validator option

**Comment by nbudin** [comment]
Adding URL validation won't be a quick fix, but we can do it.  I've added it to the backlog.

**Comment by nbudin** [comment]
I ended up solving this a little differently than expected: forms can now have "url"-type freeform text fields, and if that field has the type "url", it will automatically get linkified on display.  During that process, the component that renders it checks the URL for validity, and tries adding an `http://` if it's not there.  This seems to work reasonably well for all existing games.
