### ISSUE TITLE
Message inaccuracy when a new game cannot be added due to policy

### ISSUE THREAD

**Issue by rizwank** [neinteractiveliterature/intercode#1463]
On attempting to sign up for a third game, the following text was displayed.

![image](https://user-images.githubusercontent.com/223204/47886527-d9784a80-ddf7-11e8-90b2-b6a341713580.png)

I already had 2 games signed up for, and the proper limit was 1.

Message should be technically : You are already signed up for 2 events, which is more than the maximum allowed at this time.

Of course, the base situation shouldn't have happened in the first place.

**Comment by nbudin** [comment]
Lol, fair point!  I've fixed the underlying logic bug that caused this situation to happen, so I think this shouldn't be able to happen anymore - but yeah.  If it turns out people are still getting this message after the fix, I'll reopen this issue and fix separately.
