### ISSUE TITLE
Load queueing

### ISSUE THREAD

**Issue by rizwank** [neinteractiveliterature/intercode#1465]
While, orders of magnitude larger, Burning Man has a queuing system, the first X people on the site get a ticket and the rest are pushed onto a waiting queue.

Those X people have 5 minutes to make a selection, and as they check out, the next group of people are allowed. Each new browser session is independent of login, so waiting in line can't be gamed by having multiple browsers.

Might be an interesting idea for handling the load spike that we all encountered during initial signups. Probably too much for Intercon, but perhaps for larger cons?

**Comment by nbudin** [comment]
Yup, I've seen systems like that, and there's certainly a place for them for large events.

I do think we can get things tuned to the point where we don't need it for Intercon, and I'm going to make some major adjustments tomorrow that we'll have in place for the next signup round.  (The bottleneck tonight seems to have been connections on our Postgres server.)

**Comment by nbudin** [comment]
After signups have completed, I can pretty conclusively say the site can perform fine without load queuing, at least for Intercon's levels of load.  So, no queue/lobby system needed!
