### ISSUE TITLE
Progress bar for slots filled in LARPs is unintuitive on the single LARP view

### ISSUE THREAD

**Issue by raadler** [neinteractiveliterature/intercode#1471]
Right now when you visit a LARP and want to check out how full it is, the greyed out spots advance right to left instead of the full ones advancing left to right. As a user I took this as a LARP having way more space than it did. While having things the way they are makes sense in the multi-LARP view on the calendar so you can quickly scan things, having it go the other way in the individual page would make it a lot clearer to view, so people can see the progress bar and that the LARP is almost full.

**Comment by nbudin** [comment]
@dkapell: we'd originally done this to be consistent with the green bars in the schedule page, but I think @raadler has a point about this.  What do you think?

**Comment by dkapell** [comment]
I think we tried it both directions, and thought this was easier to read?

If you look at it as the colored spots retracting rather than the gray ones advancing, i think it makes more sense?  We weren't thinking of it as a grey progress bar, but as a number of items that were being removed.

That being said, if people are looking at it as a grey progress bar covering the color, then the other way makes sense to me.  How hard would it be to fake out the inversion as a test?

**Comment by nbudin** [comment]
@dkapell Probably not too hard to mock up; I think I won't be able to do it today though.  I'll see about mocking it up tomorrow morning.

**Comment by raadler** [comment]
I do think having it flipped would be more intuitive. I also wonder if having the spots taken in color and the spots left in gray would be even more intuitive, or if it would be confusing.

**Comment by dkapell** [comment]
I'll run this question by a few UX people in the community, and probably also set up a poll on facebook tomorrow, when more people are around.

**Comment by marleighnorton** [comment]
Spots taken in color and not available in grey is more straightforward.  And it should progress from left to right, like a progress bar filling up.

But I think we can do better.  Let me futz with some stuff...

**Comment by dkapell** [comment]
The thought had been that the bar represents availabily of slots, rather
than slots taken, as we thought that would be more valuable for attendees,
but I think we were wrong, especially because so many attendees are also
GMs, who think the other way around
--dave

**Comment by marleighnorton** [comment]
Proposal the first!  Very clear.  Shows how many possible slots for each thing rather than making it look at a glance like all buckets have the same number of slots.  Waitlist only gets the filled icons as it adds people.

Potential issues: can take up more vertical space, though I think we can squash them down pretty far before they're illegible.

<img width="500" alt="Screen Shot 2019-07-24 at 10 23 01 AM" src="https://user-images.githubusercontent.com/46982612/61801613-127ca300-adfd-11e9-8792-58b84bc23063.png">

**Comment by marleighnorton** [comment]
Proposal the second!  Same deal, a little more abstracted.  Should compress better.  Less clear, but I think pretty understandable still.
<img width="383" alt="Screen Shot 2019-07-24 at 10 31 52 AM" src="https://user-images.githubusercontent.com/46982612/61802402-5d4aea80-adfe-11e9-95ac-a97e70ba3a91.png">

**Comment by marleighnorton** [comment]
Also all that 1 of 6 stuff, that's bad.  I like the existing 5 of 6 available notation better.

**Comment by marleighnorton** [comment]
And abridged treatment for the schedule page.  Lines switch to circles as the game fills up.  Line length should equal circle diameter.

<img width="270" alt="Screen Shot 2019-07-24 at 10 46 16 AM" src="https://user-images.githubusercontent.com/46982612/61803520-49a08380-ae00-11e9-800b-7b988eaab16f.png">

**Comment by dkapell** [comment]
Some Icon Options, based on the above, from our Icon Library:
Circle outline - https://fontawesome.com/v4.7.0/icon/circle-thin
User Circle - https://fontawesome.com/v4.7.0/icon/user-circle-o (also https://fontawesome.com/v4.7.0/icon/user-circle, but that's darker, and I don't like it as much)
Filled Circle - https://fontawesome.com/v4.7.0/icon/circle
The dash doesn't exist in Font Awesome v4, but can be created via CSS as we do today.

**Comment by marleighnorton** [comment]
If you look close, the dashes have rounded edges, which I like because it makes the gap between them a little more obvious.  But if it's hard, we can do without and just space them out a little more.

**Comment by dkapell** [comment]
That's doable with css as well, yeah

**Comment by dkapell** [comment]
Adding a note that it would be useful to be able to indicate how many signups in a bucket are no-preference signups that could be shuffled to a different bucket if someone requests that specific bucket.

**Comment by marleighnorton** [comment]
@nbudin @dkapell Do either of the graphical treatments above work?  If so, shall we move this into production?

Still going back and forth on whether it should be 5 of 6 taken or 1 of 6 left, but that seems a fairly simple switch if we decide we got it wrong.

**Comment by dkapell** [comment]
I like the circles / user icons the most, because the empty circle says 'open slot' in a way that the dash doesn't.
That being said, it should be pretty easy to mock up one in the actual page, and look at how it looks at size.

**Comment by nbudin** [comment]
Agreed.  I'm a little unclear on how the version for the schedule view works, though - is that a replacement for the existing "progress bars"?  If so, do the rows need to get taller to accommodate?

**Comment by marleighnorton** [comment]
@nbudin I was arguing above for filled in circle vs line, but I think if we're doing user/empty circle, schedule page should be filled in circle/empty circle, and we make the rows a smidge taller if necessary.  We may not need to make them taller, they might be visually distinct as is.

We could also try just a smaller version of user circle/empty circle like on the event page, but I suspect that won't read as well when smallified.
