### ISSUE TITLE
{{convention.non_volunteer_runs_with_openings}} should not include events that only have unlimited buckets left

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#1472]
This is complex and probably shouldn't be done, but would be very nice

**Comment by nbudin** [comment]
I'm fine adding this capability, but I think this points at some larger questions with accessing database stuff from the CMS that we should consider in the future:

* How much flexibility of querying can we actually support from Liquid?
* How do we support that kind of thing in a performant way?  (In the current setup, the drop doing the query has no way of knowing what comes after that query in the call chain, so it's stuck with either overfetching data, or causing n+1 queries.  Neither is great.)

On the JS side, we avoid that kind of problem by using GraphQL.  Maybe it's possible to allow CMS template authors to write GraphQL queries into their templates?  Or, add a new CMS feature for "GraphQL queries" which would give CMS admins an embedded GraphQL IDE and let them access named queries from Liquid?

**Comment by dkapell** [comment]
I like the last option there, (GraphQL Queries in the CMS) quite a bit.

**Comment by nbudin** [comment]
Created #1615 for the GraphQL option.  I've written up some thoughts there; feel free to comment if you have any feedback about those.
