### ISSUE TITLE
Attendees list search by name doesn't work on mobile

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#1474]

**Comment by dkapell** [comment]
This happened to me on desktop a couple of times as well, but reloading the page seemed to resolve it

**Comment by diewald** [comment]
I've tried looking up names in the attendee list by typing into the search field and it's _never_ worked for me. I'm running on my MacBook Pro laptop, using the latest Safari on the latest OSX 10.14.1.

I type "D", hoping it will go to the top of the Ds, but it doesn't. I hit the check mark to see if that will help, and it doesn't. I type "Diewald", and it doesn't find me, without or with hitting the check mark. The same is true if I type "Diewald, Jeff". Nothing.

Ideally, this would be a smart search, where I type "D", and it goes to the start of the Ds. I type "i" and I'd get to "Dickman, David," with my name visible just below there.
