### ISSUE TITLE
Attendee search by email address results in big red box

### ISSUE THREAD

**Issue by diewald** [neinteractiveliterature/intercode#1476]
I was trying to narrow down the symptoms of 1474 I was seeing. I thought I'd erased my search by name field, as it was blank, and nothing was showing. I typed diewald@comcast.net into the email field, hit the check and I got the result below. When I closed that tab and brought up a new tab with the attendee list and tried to search just by email, it worked. If I try to put any additional information in the name search in that new tab, I get no error and no answer. So, the error below is probably the lingering result of the search problems I was seeing for 1474.

PG::AmbiguousColumn: ERROR: column reference "last_name" is ambiguous LINE 1: ...ail) like '%diewald@comcast.net%') ORDER BY lower(last_name)... ^ : SELECT "user_con_profiles".* FROM "user_con_profiles" INNER JOIN "users" ON "users"."id" = "user_con_profiles"."user_id" WHERE "user_con_profiles"."convention_id" = $1 AND (("user_con_profiles"."convention_id" = 1) OR ((1=0) OR (("user_con_profiles"."convention_id" = 1) OR ("user_con_profiles"."user_id" = 3)))) AND (lower(user_con_profiles.first_name) like '%Diewald,%' OR lower(user_con_profiles.last_name) like '%Diewald,%') AND (lower(user_con_profiles.first_name) like '%Jeff%' OR lower(user_con_profiles.last_name) like '%Jeff%') AND (lower(users.email) like '%diewald@comcast.net%') ORDER BY lower(last_name) ASC, lower(first_name) ASC LIMIT $2 OFFSET $3

**Comment by nbudin** [comment]
Sorry for the error!  That's fixed now.
