### ISSUE TITLE
Scheduling view for admins

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#1500]
It would be super spiffy to have a grid-based scheduling UI for admins to use.  This would be much easier to deal with than the current date/time picker because you could just _click on where you want to schedule the event!_

This is probably pretty hard to do so I'm pushing this to a future milestone, but it would be so nice.

For bonus points, we'd want to be able to tell Intercode when particular rooms aren't available (because they're not in the hotel contract for the whole weekend, or something like that).

**Comment by dkapell** [comment]
This also needs to support 
1) "penciled in" scheduling of events that are still in proposal
2) "penciled in" scheduling of events that are not even proposed yet (marking a space as claimed, with a note, for say, X is going to bid a game for here
