### ISSUE TITLE
Separate permissions for contact info so that concom can see email, but not addresses

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#1501]
As part of the full ACL re-work, it would be good to have 'access basic contact details' be a separate permission from 'access all contact details'

Basic Contact details: name, email, age, pronouns, phone, state?
All: above + address, DOB

IMO, members of concom should be able to generate a list of attendees, but not see people's home addresses, for example.  Also this should be configurable for GMs

**Comment by diewald** [comment]
So much for the days of mailing out character packets via Pony Express! Signups by snail mail sorted by postmark date/time - what a concept.

Are there any current use cases that need the address? 

- Mailing out raffle prizes? 
- Lost and found returns? 

Getting the address in these cases could start with an email to the person. We may not need the address PII for Intercon purposes, as we can get what we need by using the basic details. Other cons may need it.

A further thought: the state [and/or COUNTRY] name is useful for suggesting to a GM how the person is going to get to the con. If I don't hear from Alice, who lives in Massachusetts, I can try another email or escalate to a phone call. If I don't hear from Bob, who lives in Outer Mongolia, I might want to prepare a backup player. LARP Mongolia! (Consequences routinely gets signups from several different countries. The Belgians always bring great beer, just sayin'.)

The address could be used to calculate who traveled the farthest distance to the con, which has been mentioned at Consequences in the past.

**Comment by dkapell** [comment]
The idea behind this is that generic members of concom wouldn't see addresses, beyond state, but people with advanced permission, e.g the con chair, ops, gm coordinator, would.

**Comment by diewald** [comment]
I understand the idea. I'm asking if we need the address at all. Is there a use case for it? The best way to secure PII is not to hold it in the first place.

**Comment by nbudin** [comment]
Going through old tickets and I realized I did actually do this one as part of the ACL work last year.  Closing.
