### ISSUE TITLE
Add "Preview" Button for Bucket System on Proposals page

### ISSUE THREAD

**Issue by PhilipKelley** [neinteractiveliterature/intercode#1519]
The bucket system is through and robust, but it is also complex and can be intimidating. The text-based description is essential, but has to be long, cover a lot of detail, and be complex... and many people will skip RTFM.

The "Description" and a few other items have "Edit" and "Preview" buttons. I think it would be very helpful to have a "Preview" button for the currently configured buckets: click "Preview", see what the sign-up page will actually look like; click "Edit", go back and adjust; rinse and repeat.

**Comment by nbudin** [comment]
That's actually in the plans and can be rolled out quite soon!  I've been avoiding making major changes to the code while we're opening signup rounds, but expect this pretty soon after the last round.

**Comment by dkapell** [comment]
Philip, this is in progress, but very hard with the current architecture.
We're working on making button rendering client side, partly for this
