### ISSUE TITLE
Organizations

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#1619]
(Original title: Provide a mechanism to list all users who have ever signed up for a profile on any version of a convention)

I guess there's two items here:
1) provide a mechanism to tag which conventions belong to which line of conventions ('neil', 'festival', 'consequences', etc
2) Provide a report, in a convention, to get name, email, last event attended from previous and current conventions in the same line/org

After doing this, re-enable the ability to view Users (see TODO comment in ability.rb) from organizations in which you're staff for at least one convention.

**Comment by nbudin** [comment]
Spinning the reporting feature out into a separate ticket, in the interest of shipping this quicker.
