### ISSUE TITLE
Merge users

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#1629]
We now have lots of user accounts imported from old Intercons, and many of them are duplicates of existing users with a different email address that person used to use.  It should be possible to merge user accounts.  This would require:

* Selecting the "winning" account
* Merging all user con profiles into that account
* If the winning user account doesn't have a profile in a convention, but other accounts to be merged do, create a profile using that user's latest profile info
* If there are multiple user con profiles in the same convention that should be merged, merge into the winning account's profile:
  * Alert destinations from that con
  * Form response changes from that con
  * Orders from that con
  * Privileges held by all user con profiles in that con
  * Signups in that con
  * Staff positions in that con
  * Team memberships in that con
  * Tickets for that con

**Comment by dkapell** [comment]
If the user has access to the old email, this could be self-service, otherwise, it should require admin rights to do manually.

**Comment by nbudin** [comment]
Ooh, interesting idea!  I think that can be a followup; doing the admin version of this is relatively straightforward; confirming email addresses is less so.
