### ISSUE TITLE
Allow for a required acceptance of convention terms on first login to the convention site.

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#1747]
Jaelen says:

How much of a lift would it be to proactively seek consent to abide by Intercon's policies upon registration on the website? Something like a prompt that says
```I agree to abide by all Intercon and NEIL policies, and I understand that failing to abide by them may warrant action taking against me by NEIL, up to and including removal from the convention and banning from future events. https://interconlarp.org/policy```
with a required checkbox. This would not be for S, obviously, but if NEIL approves, and if it's technically feasible, I'd like to put something like that in place for T.

Dave says:
we'd want to design it in a way where the text was configurable by the event admin(s), rather than hard coded into the code itself

It should stop registering from games until accepted (or just don't allow bypass of it to use the site on first login)

**Comment by nbudin** [comment]
Yup, we can do that.  It'll probably end up being a separate database model, but it seems like a thing that's generally useful for conventions to have.  I'm a little torn on the best place to present this - making it show up the first time someone views the site while logged in seems maybe a little heavy-handed, but I think Dave is right (in Slack) that doing it at ticket purchase time is tricky to make work with comps (or free conventions like Festival).  So I think let's try the heavy-handed approach and see if anyone complains, and if not then we're fine.

**Comment by nbudin** [comment]
This is code complete.  Probably will delay on actually releasing it until tomorrow.  When I do, here's what you'll have to do to turn it on:

1. Use the new "skip clickwrap agreement" checkbox on all the pages you want logged-in users to be able to see without accepting the agreement.  I recommend at least the rules and the GM policies, but maybe some other ones too.
2. In "convention settings," add the terms you want to be shown.  I used this in my testing:

```liquid
I agree to abide by <a href="{% page_url rules %}?skip_clickwrap=true" target="_blank" rel="noopener">all Intercon and NEIL policies</a>, and I understand that failing to abide by them may warrant action taking against me by NEIL, up to and including removal from the convention and banning from future events.
```

Once you've done this, users will start being prompted to accept terms on every page load (including you, as soon as you save the settings).

**Comment by dkapell** [comment]
Once this is live, I'll take care of implementation tomorrow.
