### ISSUE TITLE
The Secret Intercon Cabal is Too Visible

### ISSUE THREAD

**Issue by diewald** [neinteractiveliterature/intercode#1756]
Under the "Staff and GM Bios," several truly suspicious people are marked as having a position as the "Autogenerated hidden proposal_committee position".

**Comment by nbudin** [comment]
Moving this into Site Content; this is most likely a bug in the CMS page.

**Comment by dkapell** [comment]
Resolved (on S and T)  This was a side effect of the change for Proposal Commitee from a permission to a position.
