### ISSUE TITLE
Player Age to be hidden from GM view

### ISSUE THREAD

**Issue by Keri-G** [neinteractiveliterature/intercode#1786]
Thanks for chatting at Arisia, Nat!  

Per our conversation, in an effort to reduce ageism in casting, we'd discussed removing Player Age as a column in the GM view.  You'd mentioned that age could be validated on the back end (over 18, over 21, etc) without being displayed to GMs.

I really appreciate your willingness to hear this issue -- ageism isn't high on the '-ism' radar in our crowd, but it is real.  I've heard players and gamewriters alike express the view that white-haired players shouldn't be given young roles.  The word 'ridiculous' gets used.  And I'm like "you can pretend that you're on a space station, or that you're a talking rabbit, but you can't imagine that someone looks younger?"  

Thank you again for all the work you do to make things go, and thank you for your willingness to take on this one more thing. :)

Cheers,

- Keri

**Comment by dkapell** [comment]
I think my suggestion for this is to replace the GM view of player age with one of:

- under 16
- 16-17
- 18-20
- 21+
- Not Specified

This gives the GMs the info they need for safety/ age restriction, but nothing further.

**Comment by Keri-G** [comment]
That could potentially work.  Is there a way to have it only show up for
games that have age restrictions?  I imagine there are folks between 16 and
20 who would prefer the privacy if age hasn't been called out as an issue
for the game.  It seems unnecessary to introduce age information to GMs if
it's not requested or content-flagged. There's so little information
provided - player name, email address and age -- that age jumps out as
seemingly significant.

So alternately, to play the devil's advocate -- could the system just
disallow people who don't fit into the allowed age bucket(s)  from signing
up in the first place?

I'm sorry to be a squeaky wheel about it, but I'd like to advocate for a
default to privacy across the age spectrum unless/until age information is
necessary and requested.

**Comment by dkapell** [comment]
Getting back to this, due to conversation on slack - It's been very minimal in the past few years.

Having it available only to con-staff means that con staff has to check every game/signup and find issues, whereas having a age bucket available to GMs allows them to raise concerns.  I agree that the information should only be visible on games with an age restriction.  In that case, if the age restriction was changed to expressed as a number (today it's a free form field), we could just display 'over age restriction' and 'under age restricion or age not specified' or something like that.  This, of course, fails at having the right behaviour for games that are age restricted in the other direction (no one over 18 unless they're the parent of another player, which we've seen), but that's a very rare use case.

**Comment by nbudin** [comment]
The issue I see with having a structured, computer-readable age restriction is that some games want to express conditional age restrictions such as "16+ or with parent's permission", or "under 18 please talk to us first".  @dkapell, do you have thoughts about how that might work with a structured field?  Maybe having _both_ a structured and an unstructured field would work, but it's a little more burden on GMs.

**Comment by dkapell** [comment]
So, it's complicated but:

Select Field: `Age Restriction` [`none` | `16+` | `18+` | `21+` | `other`]
Checkbox, only if Age Restriction is set to `none`, `16+`, `18+`: Younger Okay in some circumstances.
Text Field: Age Restriction Details.  Required if `Age Restriction` is `Other`, or if `Younger Okay in some circumstances` is checked.

GMs get age bucket (for `other`) or `Of Required Age` / `Under Required Age` / `Unknown` for the 16/18/21 options.  No visibility for `none`

**Comment by nbudin** [comment]
After some discussion on Slack with @dkapell, I think we're gonna go with just:

`Minimum age:` [optional number field]
`Text description:` [optional text field]

Text description will work exactly like the current "age restrictions" field does, and display on the event page.  Minimum age, if filled out, will produce GM-visible advisories if the user doesn't appear to be old enough to play the game (or if their age is unknown).
