### ISSUE TITLE
send proposal submission confirmation email to submitter

### ISSUE THREAD

**Issue by jhartwin** [neinteractiveliterature/intercode#1789]
When proposals are submitted, the site should send an automated confirmation email to the submitter, with customizable text.

**Comment by nbudin** [comment]
How about, not with customizable text.  At least for a first crack at this.

**Comment by dkapell** [comment]
Could it just grab a CMS partial, like the bucket system text does?

**Comment by jhartwin** [comment]
I assume it would be editable by you or Dave, just not in the web UI?

**Comment by nbudin** [comment]
@dkapell In theory, but we have never done that in a mailer before and I suspect there are complications with it.

@jhartwin If we hardcoded it, then yes, it would be editable by me or Dave (mostly me).  All conventions would end up using the same text, but I think that's probably OK for now.

**Comment by dkapell** [comment]
Something like "Thank you for submitting a {{proposal.type|humanize}}
proposal for {{convention.name}}. We will be in touch shortly.  If you
have any questions, please contact {{proposal.type.contact}}." only, you
know, not in liquid.
