### ISSUE TITLE
Odd message when dropping as a GM

### ISSUE THREAD

**Issue by PhilipKelley** [neinteractiveliterature/intercode#1876]
As a GM for a game, went to "Edit GMs", clicked on "..." for myself, selected "Remove GM". Confirmation dialog appeared reading
  Are you sure you want to remove Philip Kelley as a undefined?
Note "undefined". Selected Ok, was properly removed.

Note that this was for a game I did not originally create.

**Comment by nbudin** [comment]
Looks like this was implicitly fixed as part of the event categories feature, and I didn't notice.
