### ISSUE TITLE
Team members for dropped events still have the team member flag set

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#1915]

**Comment by nbudin** [comment]
@dkapell For clarification, what's the effect of this?  (There isn't an explicit flag that says "this user is a team member"; it's done somewhat more implicitly in the authorization system, so I'm going to have to do this on a permission-by-permission basis.)

**Comment by dkapell** [comment]
When I export the data for Badger, they're still flagged as being a GM, for
the purposes of giving GM thank-you gifts, and similar.

**Comment by nbudin** [comment]
Got it, thanks!  I think in that case we just need to add some logic to exclude dropped events from that calculation.
