### ISSUE TITLE
Site should send out an email to the GM coordinator when events are updated

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#205]
Whenever an accepted event is updated, the site should send an email to relevant people which contains the changes made, and who made them. 

For text fields, the emails should highlight which part changed, perhaps using https://github.com/samg/diffy or similar.

**Comment by nbudin** [comment]
Probably use https://github.com/nbudin/htmldiff-lcs or maybe just diff-lcs against the Markdown.
