### ISSUE TITLE
Contact Concentral-using organizations about migrating to NEIL Hosting

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#2174]
Concentral is deprecated and will be taken down.  Options I can offer to people with Concentral sites:

* Migrate to NEIL Hosting (free)
* Take down their Concentral site
* Archive their Concentral site as a static page

Organizations/people with live Concentral sites to contact:

- [x] BSCF LARP Conspiracy (Festival of the LARPs)
- [x] WPI SFS (SLAW; Miskatonic 2012)
- [x] Bubble (Dice Bubble; Time Bubble)
- [x] Paranoid & Crotchety (Chickadee; Día de los Sobres)
- [x] Alison S (Dragons Take Manhattan; Summer Larpin'; Devil Comes of Age)
- [x] Rain W (Marathon of Larp Writing; Infinite Magic Glories 2016)
- [x] Kate F (5Pi-Con larp track; Podwell)
- [x] Stephen K (RPI Theory Con)
- [x] EB (Bridgewater LARP Day)

The following cons have defunct domain names and so maybe don't need to be migrated, since their sites are down already:

- [x] LARPI (LARPI Minigames)
- [x] Genericon (Genericon; Weekend of Hell)
- [x] Foam Brain Larps (Foam Brain Minigames)
- [x] PLOT (Palindrome)

**Comment by nbudin** [comment]
Tentative shutdown date for Concentral: August 1 (two weeks after Summer Larpin’ 2019).

**Comment by dkapell** [comment]
For the defunct ones, we can offer space at convention.host if people want
them for historic reasons

**Comment by nbudin** [comment]
That’s my plan.  It’s unclear if I can even successfully contact some of these people at this point though, so I’m ok with having no migration strategy in place for sites that can’t be accessed anyhow if it comes to that.
