### ISSUE TITLE
Collect 'location' as an convention setting

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#2179]
It would be good to be able to display location in the list of all conventions, even though it is not needed anywhere on the site technically.

**Comment by nbudin** [comment]
I could think of some interesting things to do with this, particularly if we get real locations (like from the Google Maps Places Library).  One obvious one is we could auto-generate a map to display on the con site.

**Comment by nbudin** [comment]
Google has made their API unaffordable, so I did some research into alternatives with reasonable free tiers and it looks like Mapbox might be a good one.  Signed up for a free account there.  (Mostly commenting as a note to my future self whenever I get around to actually doing this.)
