### ISSUE TITLE
"Skip clickwrap" check box on page not being respected

### ISSUE THREAD

**Issue by Quinn-D** [neinteractiveliterature/intercode#2212]
This page has skip clickwrap check box selected, but a new user who is presented with the clickwrap agreement upon creating an account cannot follow the link to this page.(they are redirected back to the clickwrap)
https://2019.beconlarp.com/pages/socialcontract

**Comment by dkapell** [comment]
The link to the social contract page was a fully qualified link rather than a CMS-created link.  I corrected that, set my own accepted_clickwrap_agreement to false in the database, and it works now

**Comment by nbudin** [comment]
Thanks @dkapell - I'm curious to learn more about the details of this so I can perhaps improve the skip clickwrap feature, but it sounds like the immediate problem is solved, so I'll close this.  I'll ping you separately to figure out if there's more I can do here.
