### ISSUE TITLE
Schedule grid

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#24]
Probably for now we should port PCSG (the ProCon Schedule Generator) from Intercode 1.  (There's already a Ruby implementation of PCSG in [the ProCon codebase](https://github.com/nbudin/procon), but it is an older generation and kind of not great Ruby.)

The schedule grid is increasingly problematic in terms of scaling to the size of convention Intercon currently is, and I do want to address that, but we should at least have some kind of schedule grid right now.

It might be worth implementing the schedule grid in JavaScript, as a React component, so that the site can simply send the React component the event data as JSON.  Or maybe not.  I'm honestly not sure.

**Comment by dkapell** [comment]
IMO, sending the data as JSON / using React or similar for rendering would be the better plan.
