### ISSUE TITLE
Return to attempted page after login

### ISSUE THREAD

**Issue by jhartwin** [neinteractiveliterature/intercode#2461]
Feature request, but I have no idea how complicated this is, and if it's infeasible, this is not an issue that seriously impacts my ability to use the site. If I go to a page that requires auth, realize I'm not logged in, click the login button and log in, I'd expect it to stay on the page I was trying to access, but instead it just brings me to the front page.

I don't know if I'm explaining this well. Example:
1) Be sure you're logged out
2) Go to https://t.interconlarp.org/admin_event_proposals/2749 (and get the Not logged in message)
3) Click Login and enter your creds
4a) Expected behavior: remain at https://t.interconlarp.org/admin_event_proposals/2749 but logged in
4b) Actual behavior: end up at https://t.interconlarp.org/

**Comment by jhartwin** [comment]
github formatted my list oddly. I think my intent is clear, but let me know if it's not.

**Comment by nbudin** [comment]
Actually what you've described is how it's supposed to be working; I think I introduced some bugs in this behavior with the permissions update.  I'll flag this as a bug and put it at the top of the list.

**Comment by nbudin** [comment]
This should be fixed with the latest release.
