### ISSUE TITLE
Filters - Stop Showing Me Stuff I Can't Attend

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#2494]
Goals
- Players filling their schedule could use an easier way of figuring out what they have time for.
- Players may not be able to attend events due to arrival/departure times
- Players may not be able to attend events due to conflicting events.

Current thoughts
- Be able to set arrival and departure times in profile.  By default, set to widest range.
- Have filters on Events page to filter out events that are before you arrive/after you leave/while you're signed up for something else
- Also use shading on Schedule page to show when you're busy
- Keep in mind: some events are of a more drop in nature, and should not count as conflicts (e.g. dances, talks, gaming, consuite)  How to handle?  Sign up as "FYI?"  Let certain events not count as conflicts?

**Comment by nbudin** [comment]
This is 🔥.  It would be super helpful for people, I think.

We do have a way already to mark events as not counting for conflicts - the event can set a "can play concurrently" flag that makes it not count as a conflict for other signups.  So we could piggyback off that.

**Comment by marleighnorton** [comment]
Intercon has caught up to me.  Trying to think of the quickest, easiest improvements I can suggest.

Add a filter to the events list page that looks the same as the "All events" filter.

Text:  All times
Checkboxes
Non-conflicts only
Thursday
Friday morning
Friday afternoon
Friday night
Saturday morning
Saturday afternoon
Saturday night
Sunday morning

**Comment by marleighnorton** [comment]
If we can also add a widget to the profile, that'd be neat.  To keep it simple, I'd just have it match the time slots above.  Only used when filtering for non-conflicts.

I plan on attending:
Checkboxes
Thursday
Friday morning
Friday afternoon
Friday night
Saturday morning
Saturday afternoon
Saturday night
Sunday morning

**Comment by marleighnorton** [comment]
Chatting with @nbudin we think the profile thing won't be noticed.  We're going to make sure filter settings are included in URL so people can bookmark.

Going along with that, the title should be updated to reflect the current set of filters.  By title I mean the thing circled in red.

<img width="953" alt="Screen Shot 2019-10-18 at 11 52 36 AM" src="https://user-images.githubusercontent.com/46982612/67109261-1cb10200-f19e-11e9-8bbc-61ddb70dd885.png">

**Comment by nbudin** [comment]
We implemented this ages ago, but I forgot to close this issue.
