### ISSUE TITLE
Last minute drops/adds

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#2496]
Goal
- Last minute drops/adds during Intercon are a huge pain in the butt.  How do GMs recruit?  How do free players know GMs are looking?

Current thoughts
- Freezing the website while the con is going on is a bit odd.  The site has wifi, and likely a business center in case folks don't have a device.  Start with keeping the site live.
- Figure out sending SMS messages as well as e-mail.  I think @nbudin said he had a way to do this.
- Come up with a way for players to sign up as last minute waitlisters for multiple games (maybe let people be on multiple waitlists starting a week before con?)
- Let those players opt in to e-mail notifications, SMS, or both.
- If players are cast, automatically take them off waitlists for conflicting games.
- Drops far in advance - Handle as usual (cast someone off the waitlist)
- Drops during Intercon, let GMs specify to contact the next player on the waitlist or everyone on the waitlist.  For players, they get a SMS/e-mail saying there's an opening.  They respond y/n.  N means take them off the waitlist.  Y means they're cast (take them off of conflicting games' waitlists).  If sending to multiple, first come, first served and let them know when taken.  (maybe better to do in order and wait 30 seconds between invites, so a little less of a free for all?)

**Comment by nbudin** [comment]
Yeah, I've been wanting to stop doing site freeze for literally years.  I think there are some arguments for site freeze from the Ops end, which Jaelen or Dave might recall, but I feel like it should be possible to meet the needs of Ops without freezing the site.

We do have a potential way to send SMS via our Twilio account, which we currently use for the safety hotline.  It'd be some doing to set up but certainly within the realm of possibility.

**Comment by marleighnorton** [comment]
I really like SMS because I feel like that's best for when a player just doesn't show up and the GM has to just get a warm body in ASAP.  So ponder how hard it would be.  :)

**Comment by nbudin** [comment]
Oh, definitely doable.  I say this mostly to set expectations about how long it would take to get done, not to dissuade anyone from thinking about the feature.

**Comment by marleighnorton** [comment]
OK!  Chatting with folks, the plan for Intercon T is to turn on texts 24 hours before game start.  Notifications at that point will be sent to both e-mail and text.  There will be a link to the game page, so if people need to withdraw, they can do so fairly easily.

**Comment by nbudin** [comment]
Hey @marleighnorton, I was just going through old tickets and I think we did this one, so I'm closing it.  If there's anything more you'd like to track as part of this, feel free to reopen!
