### ISSUE TITLE
Schedule display

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#2498]
@dkapell says the schedule display needs design work. What are the problems, Dave?

**Comment by nbudin** [comment]
A lot of the discussion about this happened in #1471.  Not sure if you want to keep both issues, but it's certainly at least worth reviewing that one.

**Comment by marleighnorton** [comment]
Is it?  I was thinking futzing with progress bars and the schedule view were two different things.  Are they the same?

**Comment by nbudin** [comment]
Sorry, my bad.  This should have gone in the other issue.  🤦‍♂

**Comment by marleighnorton** [comment]
We did this!  Yay!
