### ISSUE TITLE
"Away" times from the con

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#25]
Intercode 1 lets users set themselves as "Away" during certain hours.  I'm not actually sure if this gets used by the con, and I was the fucking con chair last year, so that's probably a decent indication we don't need this feature.  If it's not needed, I would like to get rid of it.

@dkapell: any idea if this feature is actually used for anything?

**Comment by diewald** [comment]
The original idea for this was so that we could eliminate spamming these people with email about games that still needed people in a given slot. If you were “away”, you weren’t interested in signing up then.

**Comment by nbudin** [comment]
That makes sense.  Anyone know if Intercon still emails people who aren't signed up for anything in slots?

(Regardless, I think we need to rethink the UI for this if we do build it, because the way it's laid out right now makes it harder to make the schedule grid mobile-friendly.)

**Comment by dkapell** [comment]
Yes, we used it this year.  I assume it honors the "mark me away" feature,
but it might not
--dave

**Comment by diewald** [comment]
Yes, we still send these emails. We’ve done this a couple of times in the last few weeks, as new games have been added to the Q schedule. Without those emails, Will That Be All?, which I volunteered to run on Friday night, would not have hit its minimums, let alone nearly fill. Other new games have also benefited by these reminders.

There are undoubtedly better ways to handle this in the UI. 

Note that the fourth number in the second row of counts in each of the Totals in the Schedule With Counts is the number of people who checked the away box. It is being used, but not in any significant way.

Jeff

**Comment by nbudin** [comment]
Ok, thanks guys!  I'll mark this for 2.0, and think about UI options.

**Comment by nbudin** [comment]
After considering this use case some more, I think we can do this much more simply.  The goal of this feature is to allow users to opt out of receiving emails about events that need attendees.  However, almost nobody is using it (7 people at Q used it, for example) and after informally surveying some long-time attendees, none of them were aware the feature existed or could figure out what it would do if they checked the boxes.

I think this feature is offering most users a level of control and granularity that is actively harming their ability to understand it.  Rather than keeping it this way, I am going to simplify it: in the "my profile" section of the site, there will be a switch allowing users to opt out of receiving those emails.
