### ISSUE TITLE
Rename Staff and Site Admin

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#2586]
These are a bit strangely named, here's a suggestion that Jaelen and I came up with last night

Staff -> Convention Site Admin (or just Site Admin)
Site Admin -> Global Admin

**Comment by nbudin** [comment]
Reasonable.  FWIW, "staff" is going away pretty soon anyhow in favor of staff positions anyhow, but I'm happy to rename "site admin" in the frontend copy.
