### ISSUE TITLE
Replace checkbox with user icon for games where you're signed up.

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#2745]
Related to #1471 

Checkboxes as icons are always a little dicey, since they're not interactive the same way.  But luckily, due to issue #1471 we have an icon for a person signed up for a thing now.  Recommend replacing the checkbox in the case below with the circle-with-a-person icon.

![Screen Shot 2019-10-01 at 5 24 35 PM](https://user-images.githubusercontent.com/46982612/66011321-a5d2f400-e490-11e9-96ce-37d6b265ec69.png)

**Comment by dkapell** [comment]
I love this idea.
