### ISSUE TITLE
Feature Request: Wiki style diff history for proposals

### ISSUE THREAD

**Issue by jhartwin** [neinteractiveliterature/intercode#2770]
jaelen (they/them/their/themself):turtle: 5:33 PM
Feature request that may or may not make sense; I'm happy to make a github issue but I want to make sure it makes sense first. When proposals are changed, I get an email describing the changes. I'd love to be able to click a button on the website and review that edit history, so I can more easily see what's changed even if I missed or accidentally deleted the email.
Hm. That was easier to explain than I thought it would be.
quinn 5:33 PM
Omg, yes, that!
chadberg 7:48 PM
Wiki style diff history?
jaelen (they/them/their/themself):turtle: 7:53 PM
that'd work
Dave Kapell (He/Him/His) 9:12 PM
I'll let Nat answer for real, but the data behind that is a little weird
remember than when a proposal changes, the site saves each change when you move to the next field, the emails are: "once an hour, roll up all changes, and email them out".  I don't remember if it then deletes the history, so it doesn't grow too large
real history is often done by saving reverse diffs, which would be a restructuring of how the data is saved.
I'd say enter a suggestion issue so it can be scoped

**Comment by nbudin** [comment]
This is possible but fairly complex to do.  I'll put this in the backlog, unless anyone wants to advocate for this being important enough to prioritize sooner.

**Comment by jhartwin** [comment]
While a wiki-style diff history would be amazing, even just collecting the summary emails as they're generated and linking to them from the proposal form would be neat. No reverse diffs necessary, just individually list all prior edits in timestamp order, and add new ones to the list as they're generated, without worrying about reconciling them with earlier ones. I don't know if that would be simpler to implement, but I figured suggesting it couldn't hurt.

**Comment by nbudin** [comment]
@jhartwin Interesting, and thanks for the suggestion!  I'm not entirely sure whether it ends up being more or less complex to implement.  (I suspect that with the tradeoffs involved, it might wind up being about the same complexity.)
