### ISSUE TITLE
Port navigation bar to frontend rendering

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#2776]
Right now the contents of the navigation bar is mostly decided by the backend, and sent over the wire as very literal GraphQL types that map to Bootstrap elements and classes.  There's no real reason we couldn't do the logic for this stuff on the frontend, and indeed we're already doing some of it.  Additionally, Skylight shows that the navigation bar query is one of our slower requests, so doing more of this stuff on the frontend should speed up site loads.

**Comment by dkapell** [comment]
Right now the nav bar renders and works before the page actually loads,
which is useful if you want to navigate to a new page.  If it's rendered on
the front end, it should be equivalently fast or the whole site will
actually feel slower.  Probably disconnecting it from the main page load
will help with that.

**Comment by nbudin** [comment]
It's true, but only because we actually block the rest of the page on the navbar loading.  One of the things I'm thinking of as part of this is to consolidate whatever the navigation bar needs into the root query we do to load the content we need to display anything whatsoever on the site (this one's invisible and blocks the main page load too), so we would have one fewer query to run.
