### ISSUE TITLE
Better way to display event names for short events

### ISSUE THREAD

**Issue by jhartwin** [neinteractiveliterature/intercode#2824]
![image](https://user-images.githubusercontent.com/10345442/67064639-4f74df00-f139-11e9-948b-63647719584a.png)

**Comment by dkapell** [comment]
I

**Comment by nbudin** [comment]
Oof.  This is a tricky one.  @marleighnorton, I'd love to hear your thoughts on what, if anything, could be done about this.  @jhartwin, is that, like, a 5 minute event?

**Comment by dkapell** [comment]
10 minute event

**Comment by jhartwin** [comment]
It's Adina's Havdalah event, which consists entirely of:
* waiting for sunset
* lighting a candle
* saying a short prayer
* immediately extinguishing the candle.

Realistically is will likely take less than 5 minutes, and it would be nice if the schedule could let people know precisely what time the ritual was going to happen. That said, if the answer ends up being "Ask Adina if she minds it being listed as a 30 minute event on the schedule, with a more precise time in the event description," that is probably a perfectly valid solution; I can't think of many use cases where we'd specifically need to actually display a box that spanned less than 30 minutes on the chart.

**Comment by marleighnorton** [comment]
Wow.  That's ugly.  I hadn't realized we had such short games.

Can we have a minimum length, at least for the display?

My other thought is to run the text off the end, but that'll get ugly if there's something scheduled right afterward.

**Comment by jhartwin** [comment]
(Technically, it's a social event, not a game; I don't think we have had a 10 minute game before, though if one were proposed, I think I'd be willing to consider it.)

If the choices are minimum length or let the text run off the end, I strongly prefer minimum length. (And if that's the case, I don't know that any code changes are necessary, unless y'all decide you want to enforce that minimum automatically.)

**Comment by nbudin** [comment]
OK.  We'll keep talking about whether this is a thing we want to figure out a design fix for, but @jhartwin given that that's your preference, please change the event to 30 minutes in the system.  (Enforcing a minimum length is certainly something I'd consider but initially I'd like to see if we couldn't find a more elegant solution.)

**Comment by jhartwin** [comment]
At-least-partial possible usability mitigation you probably have already thought of: Hovertext, so if an event name is longer than the event slot has room for, you can see the full name by hovering your mouse over the event.

**Comment by dkapell** [comment]
Hovertext is tricky (a bad idea) on mobile, which we're trying to solve for
as well.  if you actually click, you get the name

**Comment by marleighnorton** [comment]
To clarify, I don't think we should force the event itself to be 30 minutes, I think just when displaying on the schedule, we should show it at last a 30 minute worth of pixels wide.

**Comment by nbudin** [comment]
Oh yeah, that's a good idea - thanks @marleighnorton!  Here's how it looks after doing that.  Everyone OK with this possible solution?

![Screen Shot 2019-10-18 at 12 57 21 PM](https://user-images.githubusercontent.com/7477/67124227-fba0df00-f1a6-11e9-895b-4be85600d63b.png)

**Comment by marleighnorton** [comment]
I dig it!  I mean, it's not perfect, but it looks intentional whereas before it looked like a bug.  :)

And it's wide enough to tap on, which was also an issue.
