### ISSUE TITLE
Add a note to the schedule page

### ISSUE THREAD

**Issue by jhartwin** [neinteractiveliterature/intercode#2828]
Ideally it would be toggleable and editable in CMS. If it needs to be hard-coded, it should be set to be visible only as long as the schedule is not publicly viewable, and say "NOTE: This is not the final schedule. We expect to add many more games and events before the convention. Games and events that are already on the schedule may change rooms to address conflicts."

**Comment by nbudin** [comment]
Slightly alternate idea on this that would accomplish the same thing: make the schedule pages CMS pages themselves, with a new tag (or 2 or 3) to drop a schedule grid onto the page.  @dkapell, any thoughts about this as our resident CMS maven?

**Comment by dkapell** [comment]
there's some foot-shooting that's possible with that, but it could work.
Concerns:
1) rendering time, if the page has to pass through liquid
2) do we want to disallow those tags on other pages (or allow them, with a
'only these event categories' versions)
3) we want the schedule to be a top-level page, not under /pages/
4) providing a place to enter some text that shows up in an <div
class="alert"> is more user friendly than "here's a page, figure out the
HTML you want", although we do that almost everywhere else.

**Comment by jhartwin** [comment]
What are the chances of this happening ASAP? I don't know how much work it is, but I'd love the note to be available by Monday when I plan to open the schedule to GMs, if that's feasible. (Sorry if I should have been more explicit about then when initially filing the issue.)

**Comment by nbudin** [comment]
OK, since it's urgent I'm just doing this in the suggested way.  We can revisit later.  If you add a partial called precisely the string `pre_schedule_text`, that magical name will trigger it to appear above all versions of the schedule.  I'll be deploying this shortly as soon as it builds.
