### ISSUE TITLE
Export all events in spreadsheet format

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#2829]
@nbudin @dkapell 
This one is meant to fix similar problems as #2493 so if we can only do one, do that, since I think it's a better investment.  But if it's simple, and I suspect it is, it would be handy for power users.

Basically just have a button on the top of the list of events page that lets you download a spreadsheet with all the events on it.  

I'm not sure what all the fields are that we have, but here's the ones that come to mind.

Timestamp added (they're all unique, right?)
Title
Link to event page
Type (LARP, Social event, etc)
Day starts
Time starts
Day ends
Time ends
GM/Hosts
Authors
Max attendees
Summary

Anything else that should be in there?

**Comment by jhartwin** [comment]
These fields would not be directly helpful for addressing #2493 , but I could see other uses of the export that power users might want them for:

room(s)
signup status (so the spreadsheet can tell you which games you're signed up / waitlisted for)

**Comment by dkapell** [comment]
From FB - "FYI one thing that I've found useful is an export of the event list in general. I put them in google docs and my friends and I use that to discuss our bids.
It's a pretty easy filter of the JSON to do manually, but if it's possible to do a CSV/XLS export in the future, that'd be neat."

**Comment by marleighnorton** [comment]
Yeah, I suspect there are folks who want things just so, and the ratings we have integrated won't be enough for them.  An export would be nice.  Won't catch the new games, but at that point, it's up to the user to maintain.

**Comment by dkapell** [comment]
Making a note that this should be prioritized higher, if possible. (and include the fields that have been exposed as filters)
