### ISSUE TITLE
Show game length when not scheduled

### ISSUE THREAD

**Issue by Quinn-D** [neinteractiveliterature/intercode#2834]
Accepted events that have not been scheduled(or schedule is not visible to user) do not indicate their length, while attendees going through game listings before schedule is visible to them would like to know this information.

**Comment by nbudin** [comment]
Good call.  I'd like to get some input from @marleighnorton on how/where this information should go, though.  Any thoughts, Marleigh?

**Comment by marleighnorton** [comment]
A fine plan!  In fact, such a fine plan that we should have that available regardless of whether the schedule is out.

Let me rummage and see if there's a recommended place to put it.

I assume unlike schedules, we're fairly confident in game lengths such that it won't change and can publish it with the game?

**Comment by dkapell** [comment]
Event length is part of the event record, and while it can change, it
changes the same way the event title, description, etc changes

**Comment by marleighnorton** [comment]
I feel like that's not such urgent information that we need to put it on the event list page.  It can be on the game detail page as part of the list of details.  I do not have a strong opinion on order, so whatever order it is on the form is fine.

**Comment by nbudin** [comment]
It ends up that what controls what shows up on the event page is based on the form - specifically, which parts of the event form have a "public description" on them.  I'd forgotten to make this possible to change in the new form editor, so I added that (along with "admin description" which is the flip side of that coin).

Now that I've done that, I'm going to ship that and use that feature to make Event Length appear on the page for all our event categories at Intercon T.

**Comment by nbudin** [comment]
This is now complete: length appears for all larps, Forum events, and Hospitality events on their individual pages.
