### ISSUE TITLE
Event List:  Time should always be in upper right of the box

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#2835]
Event list view

It's good to have things in the same location for each event box as folx skim for info.  Usually the time is in the upper right corner of the box, which I think is a good place for it.  I've noticed for very long titled games (or very narrow screens), some of the events will move the start time to the next line.  

<img width="952" alt="Screen Shot 2019-10-21 at 2 42 38 PM" src="https://user-images.githubusercontent.com/46982612/67233553-7836f600-f411-11e9-819f-1f88fc243143.png">

Could we keep the time in the same spot, but just start the wrapping earlier?  Not as early as the image, but you get the idea.

<img width="952" alt="Screen Shot 2019-10-21 at 2 42 38 PM" src="https://user-images.githubusercontent.com/46982612/67234106-7d487500-f412-11e9-8497-12720cc6d865.png">

We could also abbreviate day names to save space (Fri|Sat|Sun instead of Friday|Saturday|Sunday).

Note we might want a similar technique for GMs/Authors/Organization, since the bottom left of the header box is a good place for our ratings when we have them (#2493).

**Comment by nbudin** [comment]
I knew there was one I was forgetting to close!  Since the interest ranking rework of the list view, this is now the case - time is always in the upper right.
