### ISSUE TITLE
Event page:  If Age Restrictions is empty, write "None"

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#2836]
Leaving fields blank can sometimes be perceived as undecided or a bug.  

<img width="434" alt="Screen Shot 2019-10-21 at 2 54 47 PM" src="https://user-images.githubusercontent.com/46982612/67234243-ca2c4b80-f412-11e9-8e58-7454b316200f.png">

Currently it looks like we always show the Age Restrictions field, even if it's blank.  If we're doing that, we should put "None" in if it's blank.

We could also arguably not show the field at all if it's blank, but I assume there's a reason we're always showing it.

**Comment by nbudin** [comment]
There isn't really a deliberate reason we're always showing it, so I'm gonna go with the "not show the field at all" option here.
