### ISSUE TITLE
Add a "hide team members" flag for events

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#2841]
It's fine if there's no UI for this for now.

A larp GM has requested to be able to hide their name from the public Internet for privacy reasons.  Let's add a simple database flag on the `events` table that will prevent their name from being published.

**Comment by nbudin** [comment]
It turns out we actually already have the capability to do this.  Team members can deselect the "display" flag.  Dave and I just tested that this works correctly even when you do it with every team member in an event, so I think that will solve this use case.

**Comment by dkapell** [comment]
Screenshot of the suggestion
![Screenshot 2019-10-22 11 21 44](https://user-images.githubusercontent.com/226454/67302123-66f7f300-f4be-11e9-9c71-2c46c06a23c5.png)
