### ISSUE TITLE
look into Unicode normalization stuff for Postgres

### ISSUE THREAD

**Issue by jhartwin** [neinteractiveliterature/intercode#2886]
ref. the conversation that starts at https://interactiveliterature.slack.com/archives/C0R87HYUW/p1572887925211400 about `Lodz` not being the same thing as `Łódź`

**Comment by nbudin** [comment]
Note to my future self: https://www.postgresql.org/docs/current/unaccent.html

**Comment by nbudin** [comment]
Oops, forgot to close this after doing it.
