### ISSUE TITLE
Unable to convert badge to an event provided badge

### ISSUE THREAD

**Issue by chadberg** [neinteractiveliterature/intercode#2899]
Tonight I attempted to convert a badge from a paid badge to an event provided one. After selecting what I believed to be all the correct selections, and pressing the 'Convert badge' button, nothing appeared to have happened. The pop up panel went away, but the badge remains as it was.

This is in the current Intercon T convention, and is for profile 138679

**Comment by nbudin** [comment]
This turned out to be a combination of a missing permission and a separate bug that was accidentally hiding authorization errors when a GraphQL mutation did a custom auth check.
