### ISSUE TITLE
Games by choice number

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#29]
I'm not putting a screenshot here for reasons that will soon become clear.

@dkapell: There's a "games by choice" page on Intercode 1 that tells you how many people picked which games in what order.  Publicizing information like that is against NEIL policy now.  Should we simply not implement this page in Intercode 2?

**Comment by diewald** [comment]
Agreed. There was also a sense that we could get some kind of statistics from it, about how many people got the choices they wanted, but I don’t think anyone ever did an analysis.

**Comment by nbudin** [comment]
Great, thanks guys!  Ditching this one.
