### ISSUE TITLE
Shouldn't Unlimited remain checked?

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#2914]
I was poking around Rabbit Run, trying to understand buckets, and saw this: 

<img width="725" alt="Screen Shot 2019-11-13 at 10 32 29 PM" src="https://user-images.githubusercontent.com/46982612/68824652-946f3100-0665-11ea-82c4-39f04000ca4a.png">

The NPCs are unlimited, yes?  That means the Unlimited box should be checked.

**Comment by dkapell** [comment]
This was either fixed by a different issue, or was a rendering issue on your end somehow.  Upon trying to verify, I can see that that box is checked, as expected
