### ISSUE TITLE
Multiple runs of a single-run non-larp event

### ISSUE THREAD

**Issue by jhartwin** [neinteractiveliterature/intercode#2940]
I want to schedule multiple runs of a single run event. There is no way to do so.

**Comment by nbudin** [comment]
Just for my understanding: is there some reason you don't want to change the event category to use the regular scheduling UI?

**Comment by jhartwin** [comment]
No, this can be closed. Dave said I should open it before y'all figured out
that solution.

**Comment by nbudin** [comment]
OK cool, thanks!
