### ISSUE TITLE
Attendance by payment amount report

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#31]
![screenshot 2017-01-29 10 27 26](https://cloud.githubusercontent.com/assets/7477/22406756/a2f13ae6-e60d-11e6-8ec1-c3b37d9d1906.png)

**Comment by dkapell** [comment]
If there are multiple time periods with the same price, it would be nice to separate them.  I.e. instead of this being a break down by cost, it would a break down of section of the time-based variable

**Comment by nbudin** [comment]
Yeah, there's effectively three dimensions here in Intercode 2: ticket type, time of purchase, and price.  However, since it's possible to adjust the price timing at any point, even after that timespan is over, it's not possible to conclusively tie timing to ticket price.  (Further, the timespans don't have names we can record.)

What I might do is first separate by ticket type, then within each timespan, separate out by price.  (I'm thinking the vast majority of ticket sales will be for the price we expect in that timespan, but having the report call out any exceptions would be nice.)
