### ISSUE TITLE
New Games -> New Events

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#3103]
Looks like our New Game widget is using inconsistent language as to whether the tab is for New Games or New Events.  New Events seems correct, so we should change the tab to that.
<img width="488" alt="Screen Shot 2020-01-04 at 11 50 37 AM" src="https://user-images.githubusercontent.com/46982612/71768895-abedcc00-2ee8-11ea-9995-fa12a0d74053.png">

**Comment by dkapell** [comment]
That's just in the CMS code for the front page.  I've fixed it
