### ISSUE TITLE
Staff misclassification

### ISSUE THREAD

**Issue by chadberg** [neinteractiveliterature/intercode#3235]
Intercon U site is listing most staff under 'Game GMs'. It appears that only the Webteam is actually listed as staff.

**Comment by chadberg** [comment]
I take it back. Not all of the Web Team is listed as staff, so it isn't that. Site admin access?

**Comment by dkapell** [comment]
This is because that page looks at if someone has ConCom privs to put them in the right bucket, and we didn't put staffers in the ConCom position when adding them to their actual positions.  correcting that fixed the page properly.
