### ISSUE TITLE
Passive display for games with openings to be used during a con

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#3255]
I'm not sure how much is intercode and how much is other config stuff, but here's where we track things, so here's where I'll throw it.

The idea is to have a dedicated monitor that shows which games still have openings.  

Design changes for web widget:
 - Auto-refresh 
 - Adjust layout to take advantage of full screen.  Maybe better headers and such.
 - Remove events in the past (or event start + 30 minutes?)
 - How to handle if the list is longer than the screen?  Do we care, since the immediate games are the most important?  Or should we flip through them if necessary, like they do in airports?

**Comment by nbudin** [comment]
Closing, cause we did this awhile back.  (@marleighnorton, if there's something about the current version that doesn't fit, please feel free to reopen.)
