### ISSUE TITLE
Create signup audit trail

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#3274]
Right now, we just have signup objects, which get changed over their lifetime, I'm envisioning a signup audit log of write-once objects, containing:

Timestamp
User
Run
Action [Signup, Withdraw, Fill from Waitlist, Convert to not counted, change bucket]
Bucket (as of/after this event)
Bucket Requested (if relevant, for signups)
Source [Self, System, GM, Con Staff] 

The SIgnup spy would be updated to use this log, (albeit just signup/fill/withdraw actions), and we could use it to track down why someone ended up in a specific bucket, etc.

**Comment by nbudin** [comment]
Believe it or not, this is a duplicate!  See #1491 for details.  I'll close this one and move the other one high on the priority list - thanks for the reminder.
