### ISSUE TITLE
I want to Give the Gift of Intercon 

### ISSUE THREAD

**Issue by stephentihor** [neinteractiveliterature/intercode#3286]
As a matter of principle I want to be able to give some form of Intercon vouchers for my staff and NPCs who want to attend Intercon or LBC/NELCO.    And for folks wher eiits a pain to spend a GM =credit or if I just want to support Intercon/NELCO/NEIL more.   I don't want to make a whole big thing of it so I am fine with some manual process but if someone feels the code --- its cool to be able to buy memberships and assign them.   If folks walk up to me I can hand them a bill suitable to the current price at the door soon but even so ... I always liek to avoid cash when feasible.

**Comment by stephentihor** [comment]
And BTW I want to buy some membership for Intercon U to be assigned later.  Just mentioning it in case the price goes up on March 8th 2020 say.

**Comment by nbudin** [comment]
This is already on the roadmap: #1351.  Closing this one as a duplicate.

**Comment by stephentihor** [comment]
Okay thanks.   I am betting it won’t make March 8th :)

**Comment by nbudin** [comment]
You will definitely win that bet.  For now, please work with the registration people for the appropriate event to pay them via some other means.
