### ISSUE TITLE
Persona L gets double popups!

### ISSUE THREAD

**Issue by valleyviolet** [neinteractiveliterature/intercode#3325]
https://t.interconlarp.org/events/schedule_by_room/saturday
Click on either instance of "Persona L: Find Your Voice" at 9am and two copies of the popup appear.  Reproduced on a reasonably recent Firefox and Safari on iOS

**Comment by nbudin** [comment]
But don't you want to find your voice TWICE?????

Adding to the backlog, thanks for reporting 😁
