### ISSUE TITLE
Change log / exportable spreadsheet for add drops between dates

### ISSUE THREAD

**Issue by kimsward** [neinteractiveliterature/intercode#3326]
The new system emails / texts gms when players add or drop the con.  This can be turned off as a notification but then information may be lost.  It would be extremely helpful if the system could generate a direct change log of who added and dropped based on inputted dates (so for example the week up to and during the con) so that comparisons between two dates / times could be easily made.  Basically a list of players who dropped and a second list of players who were added.   While it is possible to do this by exporting data at any earlier time period then again at a later one, tagging which is which, and then doing a merge of the data sets etc - it requires both remembering to perform and store an earlier pull and better computer power than most people are going to use on their cell phone.

For context, I was one of the Iron GM Coordinators.  For each session of Iron GM, we try to best balance player numbers between the 3 games that will run in that slot.  For multiple logistical reasons, it would not work to let the players do this themselves (I can go into this in more detail if wanted but it's not relevant to this request which could apply to other types of roles in different game formats)

We typically have people do some combination of tell us they aren't showing, and no show.  We then have to go recruit players during the con.  Nothing about having to rustle up more players, make announcements in the con suite or have players not show up changed except I think we had an increase in overall drops leading up to and at the start of the con.

The notifications were constant enough from about Tuesday on, that I had to turn them off on my phone because they spiked my anxiety every time I got one about having enough players to let all the games run and compete. (Contestants put a lot of heart into the games so it would be horrible if they didn't get to run them).  We had Nicole join us to help with logistics and I had initially left her off the notifications until late Saturday night --- and she thanked me for that on Sunday as it was a lot of data going back and forth and also became quickly overwhelming.  Being able to do a set pull of changes from 1 time to another would help fix this and allow for better disbursement of attendees.

**Comment by nbudin** [comment]
I actually just shipped this today!  (I didn't want to ship it before Intercon T since it's a big feature in the signup system and I didn't think the risk was worth taking.)  We'll have it going forward.

**Comment by nbudin** [comment]
(For a little more context see #1491 and #3287.)

**Comment by kimsward** [comment]
Before you close this - can you please explain how it will work?

**Comment by nbudin** [comment]
Sure.  There's a new database table called `signup_changes` that logs every version of a signup record that's been created/updated/etc.  I've pre-populated it with the end states of all existing signups, so right now it doesn't have the history, but it will start to collect it going forward.

Signup Spy now works off that table, and it's always been able to export a spreadsheet.  I've also added the ability to filter Signup Spy by event title amongst other things, so getting a trail of what's happened with all an event's signups should be straightforward.

**Comment by dkapell** [comment]
Nat - will this be usable by GMs to look just at their own game, or is it a
con-com only thing?

**Comment by nbudin** [comment]
To address your edited comment, it isn't yet available from the GM point of view, but it will be soon.

**Comment by kimsward** [comment]
okay cool - but Sign up spy isn't something I think all gms can see - so can permissions be changed

**Comment by nbudin** [comment]
OK everyone, let's please all stop typing the same comment simultaneously 😂

**Comment by kimsward** [comment]
Is it going to be in the same report area or off the event page for each game ( for ease of use a link off the gm's game page is going to be easier to explain to them / adopt so that would be my preference )

**Comment by kimsward** [comment]
OK - can you let me know when the gm version is available ?

**Comment by nbudin** [comment]
@kimsward will do!

**Comment by nbudin** [comment]
Added #3327 to track the GM-side view of this (probably not a huge lift to implement given the existing work).
