### ISSUE TITLE
Switch to Amazon SES

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#3352]
We're currently using Mailgun for both sending transactional email and forwarding inbound email.  Mailgun's new pricing structure makes routes a premium feature, so we can no longer do this without paying them $35 a month.  Fortunately, Amazon SES appears much more affordable and also lets us do something even a little cooler than Mailgun's routes.

- [x] Switch to Amazon SES for outbound email (using their REST API)
- [x] Add a "email from" setting for conventions, which will let us set the sender address for transactional emails from a domain without needing all NEIL Hosted cons to add a bunch of arcane shit to their DNS provider
- [x] Set up a webhook listener that processes incoming email received by SES, redirecting it to the appropriate staff position or event team
- [x] Allow conventions to have a "catch-all" staff position for email addresses at the convention domain that aren't taken by any other staff position
- [x] Allow staff positions to have CC addresses that aren't actually members of that position but will be CCed on emails
- [x] Allow staff positions to have multiple email aliases
- [x] Add a root-site-level `EmailRoute` model which will redirect emails not matched by a particular convention alias
- [x] Support a EOL mode for a convention, where all the individual emails get directed to a specific email address, for after a convention is done
- [x] Root site-level admin UI for EmailRoutes
- [x] Staff position admin UI for new email settings

Once this is done, we can remove the old Mailgun sync code, which never worked great to begin with.

**Comment by dkapell** [comment]
Some additional items:

- [ ] We need to be able to handle convention-series emails that redirect to the specific convention-year's emails (so hotel@interconlarp.org  -> hotel@u.interconlarp.org)
- [ ] We need to be able to handle some mailing aliases that are not tied to a convention (all interactiveliterature.org emails, for example
- [ ] we need to be able to handle mailing aliases that look like they should be tied to a convention, but aren't (signup-feedback@interconlarp.org)
- [ ] We should support a EOL mode for a convention, where all the individual emails get directed to the conchair (or whatever), for after a convention is done

**Comment by jhartwin** [comment]
I think we may want two separate EOLs. Like, emails for T should go to me for at least a year or two, but if someone sends an email to conchair@b, do we want it going to Jim White, or do we want it going to the current NEIL President?

**Comment by nbudin** [comment]
Probably EOL mode can have a setting attached to it of "email address that all the emails should go to," and we can just change the address depending on what's appropriate.

**Comment by nbudin** [comment]
@dkapell + @jhartwin, I've added some checklist items above that I think should cover the items you both mentioned.
