### ISSUE TITLE
update interactiveliterature.org with new board

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#3373]
Please update the board page on the corp site to show:

President 
Dave Kapell 
Term ends 2021
davekapell@interactiveliterature.org

Board: Term ending 2021
Jen Eastman-Lawrence - jeneastman-lawrence@interactiveliterature.org
Cyrus Nations - cyrusnations@interactiveliterature.org
Kim Sward - kimsward@interactiveliterature.org

Board Term ending 2022
John Cooke - johncooke@interactiveliterature.org
Quinn D. - quinnd@interactiveliterature.org
Adina Schreiber - adinaschreiber@interactiveliterature.org

Advisors:
Treasurer
Chad Bergeron - treasurer@interactiveliterature.org

Intercon T
Jaelen Hartwin - conchair@t.interconlarp.org

Intercon U
Alison Joy Schafer - conchair@u.interconlarp.org

NELCO 2020
Cameron Betts - nelco@interactiveliterature.org

Game Wrap
Vik Fuzaylova - gamewrap@interactiveliterature.org

For historic purposes, Dave Kapell was also president for 2019-2020, and the three people listed as end of term in 2021 were elected last year

**Comment by nbudin** [comment]
@dkapell, I think this should probably go in the https://github.com/neinteractiveliterature/interactiveliterature.org project, right?

**Comment by dkapell** [comment]
I mean, yes. i'll move it over there.  This is what I get for filing issues before coffee
