### ISSUE TITLE
Ops reports

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#34]
There are a bunch of printable reports that Intercode 1 generates for Ops.  These include:

- [x] Per-event report (includes rooms, team members, bucket fullness stats, and a list of confirmed and waitlisted attendees for each run of the event)
- [x] Per-user report (includes all the signups for each user, along with rooms, times, and confirmed/waitlisted status)
- [x] Per-room report (includes all the runs happening in that room, and when they're happening, in chronological order)
- [x] Ops report (includes who's signed up for ops when; maybe we can just make this a "compact" view of a per-event report)
- [x] ConSuite report (ditto)
- [x] Games by time report (just a list of which games are happening when, and where)

There are a couple reports here that are redundant, and we won't implement for 2.0:

* Registration report (a paper form for checking people into the con)
* Registration Checkin (which is simply a user list, each line of which links to a single per-user report)

**Comment by dkapell** [comment]
Can the per-room report please be sorted in time order, so I don't have to keep re-typing all the information in it each year if I don't want to?

Registration report is not needed by NEIL, now that we're using Badger, although a reg desk view might not be the worst plan, for other events (online checkin form)

**Comment by nbudin** [comment]
They're not?  Oh jeez.  Yes, we can do that.  I'll update the requirements above to make sure that's clear.

I think we can leave off the reg report for now; the other cons that I'm hoping to roll out 2.0 for don't do check-in at all, so they won't need it either.  It's not too hard to add later on.
