### ISSUE TITLE
Optionally-limited-use coupon codes

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#364]
I would like to be able to offer someone a reduced, but not free, ticket by some mechanism.  For example, look up the user, and mark them as being able to pay X for a ticket, instead of the standard Y.

This is to be able to offer reduced cost tickets to attendees with financial need, or in a special category.

**Comment by nbudin** [comment]
What’s your feeling on single-use coupon codes?

**Comment by dkapell** [comment]
that's a solution, I was thinking that it seems like it would be more work
to go in, create a single-use code, and hand it to someone to enter, rather
than being able to flag an existing, but unpaid account as having a
discount.   I might be wrong though

**Comment by nbudin** [comment]
Yeah, I'm thinking of potentially a way to mass-generate coupon codes and let you easily mail them out with MailChimp or something.  Tying the discount to a particular user profile seems like a too-specific solution to me, and I could see other cons wanting to offer discounts via a code, so I'm thinking of optionally-consumable coupons.

**Comment by dkapell** [comment]
sure, that works

**Comment by dkapell** [comment]
codes should have an optional limited number of uses

**Comment by nbudin** [comment]
Cool, thanks - updating this ticket.
