### ISSUE TITLE
Referring sites summary

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#37]
We currently collect HTTP referrers data for users entering the site.  I'm pretty sure we do not use the referrers data we collect for anything whatsoever.  @dkapell, can you confirm?

If we do want this kind of information, I'd suggest we install Google Analytics or some similar solution.

**Comment by dkapell** [comment]
GA is a way, way, way better solution for this, yes

**Comment by nbudin** [comment]
Great; I'll close this and make a separate issue for GA.
