### ISSUE TITLE
Proposal: Add a hidden link for online events (like, a Zoom call or something)

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#3836]
Meetup.com supports this and I think we should too.  Don't show the link publicly, but do show it for confirmed attendees.

**Comment by dkapell** [comment]
This could also be used for survey links

Maybe it should be a new field type that supports multiple links with a short description
["Zoom Meeting"] [ <Zoom Link> ]
["Casting Questionnaire"] [ < forms.google.com link> ]
["Background reading"] [<link to whatever>]
