### ISSUE TITLE
Can't upload new files

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#389]
"We're sorry, but something went wrong." when trying to upload the attached file.
![crowneplazafloorplan](https://user-images.githubusercontent.com/226454/34967998-85f0464e-fa34-11e7-91f2-19144d53a858.jpg)

**Comment by nbudin** [comment]
I didn't deliberately do anything to fix this, but I suspect it was a permissions issue of the same sort that was making deploys break.  I just tried uploading the picture and it worked, so closing this.
