### ISSUE TITLE
Can't edit user profile data for self

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#390]
It doesn't look like there's a way to edit someone else's profile data without becoming them, which is okay, but when you try to edit your own data, you get a blank screen

**Comment by dkapell** [comment]
![screenshot 2018-01-15 20 46 16](https://user-images.githubusercontent.com/226454/34968089-29111cf4-fa35-11e7-98a3-f99b32617b15.png)

**Comment by nbudin** [comment]
This was the same JS issue as was affecting the proposal form; it's fixed now.
