### ISSUE TITLE
Markdown Footnotes Syntax Not Supported in Event Description

### ISSUE THREAD

**Issue by SeamusReynolds** [neinteractiveliterature/intercode#4303]
Hello lovely Intercode team! I discovered what I tentatively believe to be a pretty small bug in creating and editing the description for an event, when it comes to trying to include "footnotes" using the Markdown syntax given in the ["quick primer on Markdown syntax is available here"](https://wordpress.com/support/markdown-quick-reference/#footnotes) link.

I attempted to utilize Markdown footnote syntax in my event description for Extracon event **BE QUEER, DO CRIMES**.

While the syntax highlighter within the editor seemed to recognize the footnote syntax...
![image](https://user-images.githubusercontent.com/622268/97928200-801fba80-1d34-11eb-9e1f-02c66fe88483.png)

The Preview tab did not correctly render said footnotes...
![image](https://user-images.githubusercontent.com/622268/97928288-b5c4a380-1d34-11eb-804a-f24b075ec9b3.png)

And the final page did not either...
![image](https://user-images.githubusercontent.com/622268/97928345-dbea4380-1d34-11eb-95e7-387d46ac54c2.png)

For some added context, I believe that that the "core" syntax of Markdown doesn't actually include support for footnotes - they're included under the "extended syntax" section in https://www.markdownguide.org/extended-syntax/#footnotes. So my suspicion is just that the Markdown engine being used here doesn't support footnotes, which is totally fine! But since the link an event creator is given as a Markdown syntax reference _does_ include footnotes, it can be confusing that the Intercode app doesn't actually support the same syntax.
![image](https://user-images.githubusercontent.com/622268/97928918-f96bdd00-1d35-11eb-9a4f-2d36f1b4208b.png)
![image](https://user-images.githubusercontent.com/622268/97928935-05579f00-1d36-11eb-8df8-8dc25ae131d7.png)

For reference (on top of the way-too-many screenshots I already included 😅 ), I've attached the original Markdown file I used for that description to this issue here as well! [eventfootnotesdesc.md.zip](https://github.com/neinteractiveliterature/intercode/files/5478530/eventfootnotesdesc.md.zip) (I'll be editing the one that's live at https://2021.extraconlarp.org/events/4834-be-queer-do-crimes/ pretty shortly)

To be extra clear, I definitely think this is a pretty small bug! I've personally found a way around it, but I wanted to make sure I documented it for y'all to know about. Thank you for all your hard work!

**Comment by nbudin** [comment]
Thanks for the bug report Seamus!  I actually think this is potentially pretty easy to fix - we're using [Redcarpet](https://github.com/vmg/redcarpet) as our Markdown renderer and it looks like I would need to turn on the `:footnotes` option.  I'm happy to do that, so I'll give it a try tomorrow!

**Comment by nbudin** [comment]
@SeamusReynolds We now support footnote syntax in production!  Thanks again for the report.

**Comment by SeamusReynolds** [comment]
@nbudin I just tried it out on https://2021.extraconlarp.org/events/4834-be-queer-do-crimes/ and it worked great _and_ looks great! As the kind of nerd who loves things like footnotes, I super appreciate you taking the time to do this! Thank you!
