### ISSUE TITLE
Improve ticket purchasing experience

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#434]
After purchasing a ticket, the user should be redirected back to the main page with a flash message that the purchase was successful in the amount of $X and a receipt was emailed to them.  They don't need to see the transaction id, or the timestamp

**Comment by nbudin** [comment]
I'd like them to get the transaction ID for our debugging purposes in case something goes weird, but that can be in the email receipt rather than on the page they get to after buying the ticket.  Other than that, implemented as specified.
