### ISSUE TITLE
get rid of 'key' for buckets?

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#445]
suggestion: Can Key just be lowercase name, and therefor hidden?  It doesn't seem to be useful at all.

**Comment by nbudin** [comment]
Yeah, it’s probably an implementation detail we can hide.  I’m going to keep it in the backend, but it’s fine with me if it’s not user visible.

**Comment by dkapell** [comment]
The only place I saw Key used was on the list of who was signed up for a game.  That should be replaced with Bucket Name. (Commenting so you can find this easier)
