### ISSUE TITLE
Setting a proposal to accepted should create the event if it doesn't exist, not just the first time

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#446]
steps to reproduce:
1) propose an event
2) accept proposal
3) delete event
4) set proposal back to under review
5) accept proposal
The event will not be created again, and there's no way to do this.  Alternately, don't allow proposals to be set back to under review once they've been accepted?

**Comment by nbudin** [comment]
It turns out what we really need to do here is give admins a way to view dropped events so they can un-drop them.  This should be possible in the scheduling UI.
