### ISSUE TITLE
Improve interface for editing existing proposal

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#449]
When editing an existing proposal, provide save, next, and cancel buttons on every page.  if you change something early on, you still have to step through every page to finish the edit

**Comment by nbudin** [comment]
You don’t, actually, but that should be somehow made clearer.  Edits automatically save immediately.  I’ll think about ways to make this easier to deal with, but ideas on that front would be very welcome.

**Comment by dkapell** [comment]
I think having a set of buttons at the bottom of each page:
[Back to Proposal Page][Next Page] 
might work fine
