### ISSUE TITLE
Allow users to select interests on account creation/user page

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#45]
When a new account is created, we should be able to ask the user to opt-in/out of N user-defined options, which are simply recorded into the database, and eventually synced with the Mailchimp API.

The Intercon use case:
I would like to receive emails about: 
Intercon [X] (default checked)
NELCO [ ] (Default un-checked)
Other NEIL initiatives [ ] (Default un-checked)

**Comment by nbudin** [comment]
Adding this to the 2.0 milestone sort of aspirationally; if we need to push this out for timing reasons we can do that.
