### ISSUE TITLE
Provide a mechanism to bill games an amount of money, that can be paid via stripe.

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#494]
for settling up at the-con food purchaces after the con, or similar.

**Comment by nbudin** [comment]
Hmm.  This sort of amounts to "build an invoicing system", and I feel like maybe there are existing invoicing systems Intercon could use that have Stripe integration.  Here's one with a free plan: https://www.invoiceninja.com/

Do you think this would work for Intercon's needs?

**Comment by dkapell** [comment]
almost certainly.  I meant to tag this as an idea, not a ready-to-go
feature request

**Comment by nbudin** [comment]
OK.  Given that this space is well-covered by existing software, I think this is out of scope for Intercode.
