### ISSUE TITLE
Add new liquid filer for staff_email_link

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#503]
We don't want to obfuscate staff emails, so lets make things easy and create a filter for:
given something like `convention.staff_positions_by_name.gm_coordinator` can generate 
`<a href='{{convention.staff_positions_by_name.gm_coordinator.email}}'>{{convention.staff_positions_by_name.gm_coordinator.name}}</a>`

or, if no email is set, just `{{convention.staff_positions_by_name.gm_coordinator.name}}`

**Comment by nbudin** [comment]
Now you can do either of:

```liquid
{{ staff_position.email_link }}
{{ staff_position.name_with_email_link }}
```

`email_link` will generate a link to the email address like [person@example.com](mailto:person@example.com) if the staff position has a designated email address, or nothing if it doesn't.

`name_with_email_link` will generate a link to the email address like [Designated Swagmaster](mailto:person@example.com) if the staff position has a designated email address, or simply "Designated Swagmaster" if it doesn't.

**Comment by dkapell** [comment]
I assume emaik_link will generate an obsfucated link if you're not signed in, but name_with will always generate a normal link?

**Comment by nbudin** [comment]
Nope, both versions will generate a regular mailto link.  I realize the naming is slightly confusing with the email_link filter, and I’m planning to rename that filter later to something like email_link_or_obfuscated_email.
		
		

		Nat
	




On Thu, Feb 1, 2018 at 5:18 AM -0800, "dkapell" <notifications@github.com> wrote:












I assume emaik_link will generate an obsfucated link if you're not signed in, but name_with will always generate a normal link?

**Comment by dkapell** [comment]
Yeah, I played around with it and realized it's a variable, not a filter,
and have now updated all the content to use these new variables to generate
links except in two places where I wanted to have the link text be
something different than either the email or the position name.
