### ISSUE TITLE
"Propose an Event" editing page jerks up and down as I type (a "saving" icon likely the culprit?)

### ISSUE THREAD

**Issue by rtblechner** [neinteractiveliterature/intercode#5250]
As I type in to edit on the "Propose an Event" page, the page jerks up and down.
It does so because as I start to type, it adds an icon at the top-right in the header, presumably a "saving" icon, and when I stop typing, that icon goes away. The icon is taller than the height of the header, and the header auto-sizes to its content. The header, in turn, pushes down all content on the page when the icon appears, and then pushed up all the content on the page when the icon disappears.

See the two screenshots for with and without the icon, and notice the header height.
This is for all pages, not just the ones in the screenshot.

<img width="1015" alt="Capture" src="https://user-images.githubusercontent.com/88514906/128427194-5256ebc4-703c-44de-bd87-4c3ef48e73cc.PNG">
<img width="986" alt="Capture2" src="https://user-images.githubusercontent.com/88514906/128427198-e536c511-745e-46f1-924f-d38a0be8d823.PNG">

Possible fixes could be:
1. Remove this icon. To me, it doesn't _really_ add anything to know it's constantly updating. Heck, the thing appears and disappears so fast, and without warning, I have no indication of what it's even doing. 
2. Make the icon smaller so it doesn't auto-scale the header.
3. Separate the icon from any auto-scaling section of the page.
4. Make the header taller, so that the icon doesn't force it to re-scale.

It's so so so annoying, because as I type, pause even briefly, and continue typing, the page is constantly jerky. 

Relevant info:
- Firefox
- Windows 10
- 3840x2160 resolution with Windows text/appearance scaled 150%.
- Zooming in and out of Firefox does not stop the issue (control-scrollwheel)

**Comment by nbudin** [comment]
Oh jeez, sorry about that!  I had noticed the loading indicator got bigger when we upgraded Bootstrap, but I hadn't put together at that point that it was going to cause this to happen.  I'll see what I can do about this, thanks for letting me know!

**Comment by rtblechner** [comment]
So glad the Bootstrap devs tested that and considered ramifications. /sarcasm

Thanks so much, Nat!

**Comment by nbudin** [comment]
I wouldn't blame the Bootstrap devs too hard - this turns out to have been a weird interaction between Bootstrap's responsive font sizes, Font Awesome 4 (which is way outdated and which I'm planning to get rid of soon), and the way I coded that form.  I have a fixed version building right now and will post here once it's on production.

**Comment by nbudin** [comment]
@rtblechner It's all set now - let me know if it's still not fixed!

**Comment by rtblechner** [comment]
Just wanted to confirm a fix, and to thank you - hopefully it saves other GMs frustrations, and/or me when I schedule + edit a second game!
