### ISSUE TITLE
Prepopulate the 'Buy a Ticket' form

### ISSUE THREAD

**Issue by chadberg** [neinteractiveliterature/intercode#533]
If a user is already logged in, prepopulate the buy a ticket form with the information we currently have for them (name, email address, phone number, zip code). This saves the attendee time and effort.

Alternatively, consider if this is the correct place to collect any of this information at all (Name and zip code might be required so the attendee can edit them to make them match the credit card records).

**Comment by nbudin** [comment]
Yeah, name and zip code are part of Stripe's card validation.  I'll see about prepopulating and/or deleting stuff.

**Comment by nbudin** [comment]
OK, that's all set.  Email and phone are gone, and name prepopulates.
