### ISSUE TITLE
Provide a 'signup preview' when picking a bucket policy

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#544]
It would be pretty useful, i think, to have a preview of what the signup area of your game will look like as you enter bucket info.

**Comment by nbudin** [comment]
I agree.  This is pretty non-trivial to do, though, since it requires porting the signup buttons code to Javascript, so I'd like to kick this down the road a bit if it's OK with you.

**Comment by dkapell** [comment]
See, if you just wrote in node, this wouldn't be an issue. 
Yes, this is fine, which is why I flagged it 'idea'

**Comment by nbudin** [comment]
Turns out I did this, but forgot to close the ticket.
