### ISSUE TITLE
Unable to add attendee from previous event

### ISSUE THREAD

**Issue by chadberg** [neinteractiveliterature/intercode#5754]
When attempting to add Terilee from a previous event (Intercon T), I am always told 'No Options', regardless of what or if I type anything in.

![Screen Shot 2021-11-01 at 9 05 43 AM](https://user-images.githubusercontent.com/1815734/139676141-0b723948-ea41-45cd-924d-976b9fb9e9e4.png)

**Comment by nbudin** [comment]
This turned out to be a permissioning issue; @chadberg has multiple Intercode accounts mostly from long-ago cons on Intercode 1, and I had given permissions to the wrong one.
