### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by cidneyhamilton** [neinteractiveliterature/intercode#6]
Travis will run all of our tests before a new build goes on Heroku, but we don't have very many! Add test coverage for existing functionality, decide on plan going forward.

Questions:
- test framework (rails default, rspec, cucumber)

**Comment by nbudin** [comment]
We now have this to a large extent, at least according to Code Climate: we have 90% test coverage using minitest!  So I'm going to go ahead and close this.  We'll keep an eye on our test coverage numbers as the 2.0 work progresses and make sure to keep them high.
