### ISSUE TITLE
Unable to add a GM to an event

### ISSUE THREAD

**Issue by PhilipKelley** [neinteractiveliterature/intercode#6104]
The following happened both with "saved" login, and after I logged out and back in (email = pkelley@kelleysonline.com):

- Went to event I am (single) GM for (FOCUS -- same happened with "All-Batman" game as well
- Clicked on "Edit GMs" (to add co-GM for FOCUS)
- Screen came back with blank screen, with only pink banner at top that contained "Cannot return null for non-nullable field Ticket.id"

If possible, please notify when I should give it another try.

**Comment by nbudin** [comment]
Sorry about this, @PhilipKelley!  This was a bug introduced by a behavioral change in Rails 7.  I'm working on deploying a fix now and will post again here when it's ready on the production servers.

**Comment by nbudin** [comment]
@PhilipKelley: I've deployed the fix to production and manually tested it using "become user" to view the page as your account.  Please give it another go!

**Comment by PhilipKelley** [comment]
@nbudin, I am now able to access that page, thanks! (Next problem: my co-GM is apparently registered with two email addresses... but that's our problem to sort out.)
