### ISSUE TITLE
Attendee list page loads even for unprivileged users

### ISSUE THREAD

**Issue by chadberg** [neinteractiveliterature/intercode#664]
I used the 'log in as user' feature to log in as a person. When I returned to the attendee listing page it did not give me an error or prevent me from seeing the page. It did do the right thing of not letting me search or see anyone else except the user I was logged in as, but it did let me see all the checkboxes and download a CSV file. Although not a bid security risk, it is at a minimum information leakage.

**Comment by nbudin** [comment]
This should be fixed now.
