### ISSUE TITLE
Event Proposals Page, event mistakenly shows "ulimited" capacity

### ISSUE THREAD

**Issue by PhilipKelley** [neinteractiveliterature/intercode#670]
Proposal for "Bound in Blood" submitted 2018-03-06 13:46.
Buckets configured for
 - 0 Male
 - 3 Female
 - 8 Flex
 - Unlimited NPC

For this proposal on the Event Proposals Page, capacity is listed as "Unlimited". It should be 11.

So, can "NPC" bet set with an attribute that says "do not count this towards game capacity"? What if some other bucket with similar meaning is set with "unlimited"?

ADDENDA

Similary, "Sound & Fury: Lament", also just submitted, was set for
 - 10 PCs
 - 6 NPCs

with a resulting game capacity of 16 (ok, 12 to 16, factoring in minimums).

How to factor in NPC needs/counts/requirements with capacity?

**Comment by nbudin** [comment]
This is going to be fixed by #633, which is next up on the queue after product sales.  Closing this ticket in favor of that.
