### ISSUE TITLE
wrong email title

### ISSUE THREAD

**Issue by jakob223** [neinteractiveliterature/intercode#6918]
Hi,

I recently signed up as a GM for the two games I'm running at Intercon U, Sit Tight and Monsters Under the Bed, and the Monsters Under the Bed email had the same subject, with the title of the wrong game in it.

Not that this affects me in any way, but, assuming it's unintentional, thought you might want to know about it.

![image](https://user-images.githubusercontent.com/4698687/194726246-bfc00dec-09ec-40a4-a5f2-ea4e01ceebb0.png)

**Comment by nbudin** [comment]
Hi Jakob!  I'm not sure whether this is actually two emails with the same subject line, or Gmail incorrectly threading two emails with slightly different subject lines.  If you hit the downward-pointing triangle next to the text "to Jakob" in each email, you should be able to confirm whether or not the subject lines are actually the same.

If you wouldn't mind checking that and letting me know, I'd appreciate it.  Thanks!

**Comment by jakob223** [comment]
Aha! You're right, it's Gmail threading things that have different subjects. Sorry for the false report.
