### ISSUE TITLE
Allow for by-bucket filtering in production of comma-separated and semicolon-separated email lists from the GM view of a game

### ISSUE THREAD

**Issue by tallakahath** [neinteractiveliterature/intercode#7153]
Right now the only options are:

- [ ] GM
- [ ] Confirmed
- [ ] Waitlisted

I'd like to have an option to separate out `Confirmed` into the buckets. I specifically have a NPC bucket which gets a different email (for obvious reasons) than the PC players. I could see other GMs wanting this feature for similar or related reasons. I understand that waitlisted players are complex as their bucket may be TBD if they're "Flex", but confirmed players have (at a given moment in time) a fixed bucket.

So then the new options would be:

- [ ] GM
- [ ] Bucket A
- [ ] Bucket B
- [ ] ...
- [ ] Watlisted

**Comment by nbudin** [comment]
Hi @tallakahath, thanks for the ticket!  This is now available in the production site and in the new Intercode 3.9.0 release.

**Comment by tallakahath** [comment]
Thank you for solving this so quickly!
