### ISSUE TITLE
Registrar unable to view attendee profile for Con Chair

### ISSUE THREAD

**Issue by chadberg** [neinteractiveliterature/intercode#7156]
When attempting to view the attendee profile for our con chair, I received the error message "An object of type Event was hidden due to permissions"

I presume there's a permissions hierarchy thing going on here, but I'd expect the con registrar to be able to view and manage the con badge for the con chair. Further, this may point to other places where the managing of profiles may be blocked when it shouldn't be.

**Comment by nbudin** [comment]
This turns out not to be a permissions bug per se, but it reveals that the registrar needs the `read_inactive_events` permission.  I've granted that permission on the Intercon U site, which should preserve it for future Intercons since we generate their sites by cloning.
