### ISSUE TITLE
Main webpage game openings show events in the past

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#7454]
Now that we're encouraging folks to check the website for openings in games, it would be nice if games in the past were hidden like they are on our electric sign.  Two screenshots, same moment in time (Friday morning)

<img width="1223" alt="Screenshot 2023-03-03 at 8 23 35 AM" src="https://user-images.githubusercontent.com/46982612/222732737-b37c7d6d-cbd1-4854-a45e-bab82a147786.png">
<img width="1223" alt="Screenshot 2023-03-03 at 8 23 29 AM" src="https://user-images.githubusercontent.com/46982612/222732741-339a7adc-d727-4e3b-bfc9-7c2f6c139d37.png">

**Comment by dkapell** [comment]
I updated the widget to do this 3 years ago and it should be working. I
will take a look at it today to figure out what's going on. We just haven't
had an event to really test it with..

**Comment by dkapell** [comment]
Sorry I misread. I thought you were talking about the My personal signups
widget. I will copy the working code from there over to the games with
openings partial later today.

**Comment by marleighnorton** [comment]
While you're in there, I find the day dividers from the digital sign page makes things much easier to read.

**Comment by dkapell** [comment]
I ended up copying the digital sign page, and changing the formatting of it to work better for the front page widget because that already had the correct logic
