### ISSUE TITLE
Ops Event UI inconsistency

### ISSUE THREAD

**Issue by ahumez** [neinteractiveliterature/intercode#8073]
When I (as Ops Chair) sign up for an Ops shift event, it signs me up "as a team member," and lists me as such on the event page. So far, so good. On the Ops event page, it lists the slots I'm signed up for as 0 of 3 filled (that is, a "team member" signup doesn't count as filling a volunteer slot). BUT on the event schedule view it lists them as 2 of 3 filled (as though the team member did fill a volunteer slot).

**Comment by nbudin** [comment]
Fixed in #8136.
