### ISSUE TITLE
Provide field on events liquid drop for 'first run time'

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#8135]
It would be helpful to add a field to the events liquid drop containing the timestamp of the earliest scheduled run of that event (or null, if no scheduled runs), for the purposes of sorting CMS content by earliest run.  The current version has that data two levels deep, (event.run[0].starts_at) which is hard to sort on in liquid.

**Comment by nbudin** [comment]
Done in a branch which I'll merge shortly; I ended up calling it `first_run_starts_at` for consistency with other field names.
