### ISSUE TITLE
Bug: Open slot widget not returning the correct data from game with multiple runs

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#8556]
To replicate:

1. Go to https://v.interconlarp.org/pages/open-slots (or https://v.interconlarp.org/, it's happening in both places.
2. Notice the game Thawing on Friday morning is reported to have three runs with openings.
<img width="308" alt="Screenshot 2024-02-08 at 10 59 45 AM" src="https://github.com/neinteractiveliterature/intercode/assets/46982612/7e759759-08ec-49e3-aede-1e564135ba38">

3. Open the Thawing event page https://v.interconlarp.org/events/5319-thawing
4. Notice how only one run has openings.
<img width="1128" alt="Screenshot 2024-02-08 at 11 01 23 AM" src="https://github.com/neinteractiveliterature/intercode/assets/46982612/1da49f75-dccb-4ea0-9afc-97e82260fe2b">

**Comment by dkapell** [comment]
Specifically, this appears to be an issue with the `convention.run_availabilities_with_any_slots` drop.

**Comment by marleighnorton** [comment]
Further data:  The Anna slots on the incorrect runs have been taking by Quinn, who is also the GM.  That's messing with things.

**Comment by nbudin** [comment]
Fixed!
