### ISSUE TITLE
There's still openings in all these great games! widget should update based on current time, like the digital sign does.

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#8656]
The digital sign of game openings updates based on current time.  The widget on the main page doesn't, which makes it harder to use.

Screenshot taken Friday of Intercon V

<img width="557" alt="Screenshot 2024-03-01 at 8 03 36 AM" src="https://github.com/neinteractiveliterature/intercode/assets/46982612/9b2887e3-cce2-4eca-aca9-77fdcbf82160">
<img width="1271" alt="Screenshot 2024-03-01 at 8 05 08 AM" src="https://github.com/neinteractiveliterature/intercode/assets/46982612/8540612c-8c6d-4ed0-ac20-47aeb8c618c7">

**Comment by nbudin** [comment]
@dkapell I think you fixed this - if not, please reopen!
