### ISSUE TITLE
Past instances of Intercon website still permit removal from games

### ISSUE THREAD

**Issue by rizwank** [neinteractiveliterature/intercode#8675]
This might be a configuration and not a Intercon issue per se, but past sites (Intercon J-T were tested) still allow withdrawals from games. I **love** the new feature of the game schedule not being locked on Thursday, continuing to be dynamic; but I don't want to rewrite history =)

**Comment by rizwank** [comment]
Oh, I can _still_ withdraw from games in V. Shouldn't withdrawal/adds be frozen after the event has completed or at the end of con? It might jus be me, but I find the past data valuable (#8676), so I'm afraid of dorking it.

**Comment by nbudin** [comment]
This is actually a duplicate of a long-standing one (#3317).  I'm going to close this one in favor of that, and grab that one off the backlog.
