### ISSUE TITLE
Allow GMs to flag buckets as visible to players in their game

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#874]
So that, for example, NPCs are clearly labeled as such in the list of players
Also, GMs should always be labeled as not counted/GM in the signup list

**Comment by nbudin** [comment]
@dkapell, for the purposes of this ticket, what do you think about just always making not-counted buckets visible in the signup summary?  (I'm not necessarily opposed to adding another field on buckets, but since it complicates things further for GMs, I'd rather avoid it if we can.)
