### ISSUE TITLE
Don't list withdraws in the signup list for a game

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#875]
Right now withdrawals are listed in the signup list, which seems odd.  see https://nelco2018.interactiveliterature.org/events/8-bound-in-blood/runs/5/admin_signups
for an example.

It may only be listing people who withdrew and signed up again however.

**Comment by nbudin** [comment]
This is the same as it ever was (and I think it's probably worth having some way to see who withdrew from larps).  Perhaps it would be better to use coloring or opacity to make it obvious which ones are withdrawn, though?

**Comment by dkapell** [comment]
No, that doesn't seem to be true.  If I look at http://interactiveliterature.org/R/Schedule.php?action=27&RunId=58&EventId=59&FirstTime=1, I don't see Rachel Nations, who withdrew from the game.

**Comment by dkapell** [comment]
Listing people who have left the game makes it harder for GMs to use the list to see who is in their game, and, as that's not indicated to players on their view of the list, will make players think that people who have dropped from their game are still in it.

**Comment by nbudin** [comment]
Huh.  I could have sworn that action in Intercode 1 had a list of withdrawals somewhere.

I certainly agree about the player-side view.  I don't agree that we shouldn't let GMs see who withdrew, but what I will do there is make it clearer visually and also default the filters to not show withdrawals.  (So, if they want to see them, they can opt in.)

**Comment by nbudin** [comment]
Actually, the player-side view already excludes withdrawals.  So really it's just the GM-side view that's confusing right now.

**Comment by dkapell** [comment]
Yes, I think we agree.  Intercode 1 didn't show you drops in any way other than emailing them to you.  As you build this, it's important to make it obvious when someone withdrew then signed up again, vs withdrew and went away
