### ISSUE TITLE
Feedbacker:  Always on page one

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#8764]
Page X of Y widget, X never updates

<img width="1130" alt="Screenshot 2024-03-24 at 12 41 16 PM" src="https://github.com/neinteractiveliterature/intercode/assets/46982612/87815ac0-35ea-495c-9297-0de673422656">
<img width="1103" alt="Screenshot 2024-03-24 at 12 41 27 PM" src="https://github.com/neinteractiveliterature/intercode/assets/46982612/f216f799-c822-414f-8764-6c21ab61810c">

**Comment by dkapell** [comment]
Weird, it totally does for me, when clicking the arrow to change question, or using the dropdown to change question.  What browser, and what was your workflow to generate this issue?
 (also that's question X of Y, not page X of Y)

**Comment by marleighnorton** [comment]
And now it's working.  Computers, bah.

Though the `Next` tooltip isn't hiding now.

<img width="251" alt="Screenshot 2024-03-24 at 2 42 10 PM" src="https://github.com/neinteractiveliterature/intercode/assets/46982612/e6a94a98-2416-4981-9dfb-b3910848a327">

Brave Browser on a Mac, for what it's worth.

**Comment by dkapell** [comment]
Fixed the Next/Prev tooltip not vanishing after click and then mouseout.
