### ISSUE TITLE
Enable react-onclickoutside for event popovers

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#914]
Comment from a site user:

> A (hopefully) small and unimportant UI suggestion for Intercode: it would be convenient if you could also click on an event's schedule block to put away the pop-up miniblurb window once you put it up, rather than finding the little X.

**Comment by dkapell** [comment]
I was also going to ask if it could be altered to only have one popup at a time, so clicking on another event would close the active one and open a new one, which will making flipping through events easier.

**Comment by nbudin** [comment]
@dkapell I've gone back and forth on it myself.  I heard some early feedback from people that they liked the ability to have multiple things open at the same time, but I can also see how it makes things harder to navigate.  It might be worth a quick poll in the Facebook group or something?

**Comment by CVRoot** [comment]
It's super-duper-extra-fussy and idk if it would be worth the effort, but I could also see the value of being able to have only one popup at a time amongst overlapping games (otherwise there's no value to multiple popups since they overlap anyway, and you're saving people the click of putting them back away), but being able to open multiples across different schedule blocks.

**Comment by nbudin** [comment]
@CVRoot Super duper extra fussy it may be, but I've got it working.  In the new "underlap" branch, which will soon go to production if it passes the automated tests, the behavior is now:

* Clicking on a run you're already viewing the details popup for will dismiss the popup
* Clicking on a run to open the details popup will automatically dismiss the details popups for any simultaneous runs
* The state of which popups are showing persists when switching to a different day and switching back (might or might not keep this)
