### ISSUE TITLE
Enable convention admins to email the full list of signed-up attendees

### ISSUE THREAD

**Issue by OffSide7** [neinteractiveliterature/intercode#915]
The NELCO website could use a method for someone to email everyone who has signed up to PC a boffer LARP at LBC.

**Comment by nbudin** [comment]
To do this fully would require being able to search in the mailing lists for people registered in buckets with particular names, which seemed too complicated for what NELCO would have actually needed there (based on what we actually did, which is emailing all the attendees and saying "if you're registered as a PC, do blah").  So instead I've implemented a much simpler mailing list that just emails all ticketed attendees.
